# -*- coding: utf-8 -*-
"""model_comparison.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JaarQJe3gLsh-Eg3CfFUd5FviXspTO6Z

# Model comparison — trend classification across horizons

Compares the trend classifiers on the **OFI** feature stream over the label
horizons **k ∈ {10, 20, 50, 100}**:

| tag | class | family |
|-----|-------|--------|
| `dla + ofi`            | `DLA`            | attention encoder–decoder |
| `tlob + ofi`           | `TLOB`           | temporal/spatial transformer |
| `binctabl + ofi`       | `BINCTABL`       | bilinear + BiN |
| `ctabl + ofi`          | `CTABL`          | bilinear temporal attention |
| `deeplob + ofi`        | `DeepLOB`        | CNN + inception + LSTM |
| `jumpgatelob + ofi`    | `JumpGateLOB`    | jump-diffusion score matching + noise-consistent classifier |
| `alphastablelob + ofi` | `AlphaStableLOB` | α-stable joint diffusion-classifier |

Every model exposes `predict(batch, device) → (B, 3) logits`, so the metrics
(accuracy, macro-F1, per-class F1, confusion) are computed identically.

**Sections**
1. Setup & checkpoint registry (auto-discovered, editable)
2. Load models + build the shared per-horizon test set (incl. per-window realized trend)
3. Overall metrics (accuracy / macro-F1 / per-class F1) across horizons
4. Confusion matrices
5. Metric-vs-horizon curves
6. Extreme conditions (jumps) — performance on turbulent windows
7. Financial / trading metrics — MCC/κ, signal quality, mid-price prediction
   overlay, calibration & confidence gating
8. Final model comparison table

> Run from the **Penny repo root** so the `data/` cache and `checkpoints/`
> relative paths resolve.

## 1. Setup
"""

import os
import sys
import json
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import torch
import torch.nn.functional as Fn
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
from pandas.io.formats.style import Styler
from sklearn.metrics import (
    cohen_kappa_score,
    confusion_matrix,
    f1_score,
    matthews_corrcoef,
    recall_score,
)
from torch.utils.data import DataLoader

warnings.filterwarnings("ignore")
pd.set_option("display.float_format", lambda v: f"{v:.4f}")


# --- notebook `display` -> stdout ---------------------------------------------
# The cells below were written for a kernel, where IPython injects `display` as a
# builtin; running the same code as a script it is simply undefined. Tables are
# handed over either as a DataFrame or as a Styler. The Styler's colour gradients
# have no terminal equivalent, but its `.format()` string does matter — without
# it the p-value tables would print through pandas' global 4-decimal float format
# and every small p would collapse to `0.0000` — so re-apply the Styler's own
# per-cell formatters to its data and print that.
def display(obj):
    """Print `obj` the way the notebook would render it."""
    if isinstance(obj, Styler):
        data = obj.data
        formatted = data.astype(object)
        for (i, j), fmt in obj._display_funcs.items():
            formatted.iat[i, j] = fmt(data.iat[i, j])
        obj = formatted
    print(obj.to_string() if isinstance(obj, (pd.DataFrame, pd.Series)) else obj)


# --- locate the repo root and chdir into it -----------------------------------
# Jupyter kernels default their cwd to wherever the server was launched (often
# the notebook's own directory, e.g. `notebooks/`), NOT the repo root. Config
# files store paths like "data/resampled/coinbase" that `build_cache` resolves
# against the *live process cwd* — so if we only add `src/` to sys.path without
# also chdir'ing, imports succeed but data loading fails with a confusing
# "parquet not found" error. Walk up from cwd to find `pyproject.toml` and
# chdir there so every relative path in every config resolves the same way
# regardless of how this notebook was launched.
def _find_repo_root(start: Path) -> Path:
    for p in [start, *start.parents]:
        if (p / "pyproject.toml").exists() and (p / "src").is_dir():
            return p
    raise RuntimeError(
        f"could not find the Penny repo root (pyproject.toml + src/) above {start}"
    )


REPO = _find_repo_root(Path.cwd())
os.chdir(REPO)
sys.path.insert(0, str(REPO / "src"))
print("repo root:", REPO)

from crypto.dataset import build_datasets  # noqa: E402
from crypto.features import extract_features, n_features  # noqa: E402
from crypto.labels import compute_trend_series  # noqa: E402
from crypto.loader import build_cache  # noqa: E402
from models.alphastablelob import AlphaStableLOB  # noqa: E402
from models.ctabl import CTABL  # noqa: E402
from models.binctabl import BINCTABL  # noqa: E402
from models.deeplob import DeepLOB  # noqa: E402
from models.dla import DLA  # noqa: E402
from models.jumpgatelob import JumpGateLOB  # noqa: E402
from models.tlob import TLOB  # noqa: E402
from models.linvar import LinVAR  # noqa: E402
from models.logreg import LogReg  # noqa: E402
from models.ofsatnet import OFSATNet  # noqa: E402
from models.gaussgatelob import GaussGateLOB  # noqa: E402

if os.getenv("PENNY_DISABLE_CUDNN", "").strip().lower() in {"1", "true", "yes"}:
    # DeepLOB contains an LSTM. Keep CUDA available but route the LSTM through
    # PyTorch's non-cuDNN implementation on hosts where cuDNN cannot initialise.
    torch.backends.cudnn.enabled = False

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("device:", DEVICE)
if DEVICE.type == "cuda" and not torch.backends.cudnn.enabled:
    print("cuDNN disabled via PENNY_DISABLE_CUDNN; CUDA inference may be slower")


# --- figure output ------------------------------------------------------------
# Every plot below is also written to disk as a vector PDF. Type-42 (TrueType)
# fonts keep the text selectable and embeddable, unlike matplotlib's default
# Type-3 fonts, which many venues reject.
plt.rcParams["pdf.fonttype"] = 42
plt.rcParams["ps.fonttype"] = 42

FIG_DIR = (
    REPO / "outputs" / "figures" / "crypto" / "coinbase" / "btcirt" / "model_comparison"
)
FIG_DIR.mkdir(parents=True, exist_ok=True)
_FIG_SEEN: dict[str, int] = {}


def _fig_slug(fig) -> str:
    """Filename stem derived from the figure's own title.

    Most plots here are drawn inside a loop and title themselves with the loop
    variable (``f"... k={k}"``), so slugging the *rendered* title is what keeps
    the per-iteration PDFs from overwriting each other.
    """
    get = getattr(fig, "get_suptitle", None)
    text = get() if callable(get) else ""
    if not text and fig.axes:
        text = " ".join(a.get_title() for a in fig.axes if a.get_title())
    slug = "".join(c if (c.isascii() and c.isalnum()) else "_" for c in text.lower())
    while "__" in slug:
        slug = slug.replace("__", "_")
    return slug.strip("_")[:70] or "figure"


def save_fig(fig, name: str | None = None) -> Path:
    """Write `fig` to ``FIG_DIR`` as a vector PDF; returns the path.

    Repeated stems get a numeric suffix so two different figures that happen to
    share a title never clobber one another. The counter lives in the kernel, so
    a clean top-to-bottom run always writes the unsuffixed names; re-running one
    cell mid-session appends ``_2``, ``_3``, … instead of overwriting.
    """
    stem = name or _fig_slug(fig)
    seen = _FIG_SEEN[stem] = _FIG_SEEN.get(stem, 0) + 1
    out = FIG_DIR / (f"{stem}.pdf" if seen == 1 else f"{stem}_{seen}.pdf")
    fig.savefig(out, bbox_inches="tight")
    print(f"saved → {out.relative_to(REPO)}")
    return out


"""## 2. Registry & checkpoints

`MODELS` maps each tag to its class. `HORIZONS` are the label-`k` values.

`CHECKPOINTS[model][k]` is a path to a checkpoint **directory** (containing
`best.pt`) or the `best.pt` file itself. It is auto-populated by scanning
`CHECKPOINT_ROOT` and reading each run's sibling `config.json` for
`(feature_mode, label_k, symbol)` — the newest run wins. **Edit the printed dict
to point at the exact checkpoints you want.**
"""

FEATURE_MODE = "ofi"
SYMBOL = "BTCIRT"
HORIZONS = [10, 20, 50, 100]
BATCH = 256

# tag -> (class, checkpoint-dir prefix written by the train scripts)
MODELS = {
    "dla": (DLA, "dla_"),
    # "axial": (AxialLOB, "axiallob_"),
    "tlob": (TLOB, "tlob_"),
    "ctabl": (CTABL, "ctabl_"),
    "binctabl": (BINCTABL, "binctabl_"),
    "deeplob": (DeepLOB, "deeplob_"),
    "alphastablelob_1.5": (AlphaStableLOB, "alphastablelob_joint_a1.5_"),
    # "alphastablelob_1.7": (AlphaStableLOB, "alphastablelob_joint_a17"),
    "linvar": (LinVAR, "linvar_"),
    "logreg": (LogReg, "logreg_"),
    "jumpgatelob": (JumpGateLOB, "jumpgatelob_"),
    "ofsatnet": (OFSATNet, "ofsatnet_"),
    "gaussgatelob": (GaussGateLOB, "gaussgatelob_"),
}
MODEL_ORDER = list(MODELS)
MODEL_INDEX = {tag: i for i, tag in enumerate(MODEL_ORDER)}
LABELS = ["down", "stationary", "up"]
DISPLAY = {m: f"{m} + {FEATURE_MODE}" for m in MODELS}

# where to scan for runs (change if your checkpoints live elsewhere)
CHECKPOINT_ROOT = REPO / "checkpoints" / "coinbase" / SYMBOL

# JSON config used only to BUILD the shared test set for each horizon.
# Any model's ofi config for that k works (identical data params); jumpgatelob
# ships one per horizon.
DATA_CONFIG = "configs/crypto/coinbase/jumpgatelob/btcirt_{fm}_k{k}.json"


def _run_config(run_dir: Path) -> dict | None:
    """Read a run's sidecar config.json (falls back to best.pt if absent)."""
    cj = run_dir / "config.json"
    if cj.exists():
        try:
            return json.loads(cj.read_text())
        except Exception:
            pass
    bp = run_dir / "best.pt"
    if bp.exists():
        try:
            return torch.load(bp, map_location="cpu", weights_only=False)["config"]
        except Exception:
            pass
    return None


def discover_checkpoints() -> dict:
    """tag -> {k -> newest matching run dir}, matched on prefix + config."""
    found = {m: {} for m in MODELS}
    if not CHECKPOINT_ROOT.exists():
        print(f"! CHECKPOINT_ROOT does not exist: {CHECKPOINT_ROOT}")
        return found
    for run in sorted(CHECKPOINT_ROOT.iterdir()):  # lexical == chronological
        if not run.is_dir():
            continue
        for tag, (_cls, prefix) in MODELS.items():
            if not run.name.startswith(prefix):
                continue
            cfg = _run_config(run)
            if cfg is None:
                continue
            k = cfg.get("label_k")
            if (
                cfg.get("feature_mode") == FEATURE_MODE
                and cfg.get("symbol") == SYMBOL
                and k in HORIZONS
            ):
                found[tag][k] = str(run)  # newest overwrites
    return found


CHECKPOINTS = discover_checkpoints()
print("Auto-discovered checkpoints (edit below if needed):\n")
for m in MODELS:
    row = ", ".join(f"k{k}:{'✓' if k in CHECKPOINTS[m] else '—'}" for k in HORIZONS)
    print(f"  {DISPLAY[m]:<24} {row}")
CHECKPOINTS

"""## 3. Load models & evaluate

The test set is built **once per horizon** and shared across all models, so
every model is scored on the identical windows and labels. For each window we
also record a **stress score** — the repo's own market-jump measure
(`_data_jump_flag`): the largest 1-step increment of the level-averaged feature,
in realized-volatility units. Higher ⇒ more turbulent input.
"""


def load_ckpt(path: str):
    p = Path(path)
    if p.is_dir():
        p = p / "best.pt"
    # Keeping the checkpoint state dict on CPU avoids holding two copies of
    # every model on the GPU while `cls(...).to(DEVICE)` is initialising it.
    # This is especially important for DeepLOB, whose LSTM initialises cuDNN
    # weights during `.to(DEVICE)`.
    return torch.load(p, map_location="cpu", weights_only=False)


def build_model(tag: str, ckpt: dict):
    cls, _ = MODELS[tag]
    model = cls(ckpt["config"]).to(DEVICE)
    model.load_state_dict(ckpt["model"])
    model.eval()
    return model


_DS_CACHE: dict[int, tuple] = {}
# META[k] = {"mid", "ts", "centres", "trend", "alpha"} — per-window financial
# ground truth: `centres` indexes each test window's label bin into the full
# `mid`/`ts` series; `trend` is the realized smoothed trend_ratio at that bin
# (the exact quantity the ±alpha label thresholds), used by section 7.
META: dict[int, dict] = {}


def test_set(k: int):
    """(test_ds, y_true, stress) for horizon k — built once, then cached."""
    if k in _DS_CACHE:
        return _DS_CACHE[k]
    cfg_path = REPO / DATA_CONFIG.format(fm=FEATURE_MODE, k=k)
    cfg = json.loads(cfg_path.read_text())
    _, _, test_ds, alpha, meta = build_datasets(cfg)
    loader = DataLoader(test_ds, batch_size=BATCH, shuffle=False)
    ys, ss = [], []
    for b in loader:
        x = b["x"].float()  # (B, 1, T, F)
        agg = x.squeeze(1).mean(-1)  # (B, T) level-averaged stream
        dif = agg[:, 1:] - agg[:, :-1]
        rv = dif.std(dim=1).clamp_min(1e-8)
        ss.append((dif.abs().max(dim=1).values / rv).numpy())
        ys.append(b["label"].numpy())
    y_true = np.concatenate(ys)
    stress = np.concatenate(ss)

    # financial ground truth: mid series + realized trend at each window centre
    feat, mid, ts = build_cache(cfg, extract_features, n_features, tag="lob")
    centres = np.asarray(test_ds.starts) + cfg["T_past"] - 1
    trend = compute_trend_series(mid, k)[centres]
    lab_chk = np.where(trend > alpha, 2, np.where(trend < -alpha, 0, 1))
    mism = float((lab_chk != y_true).mean())
    if mism > 1e-3:
        print(f"  ! label/trend mismatch {mism:.2%} — check alpha/config alignment")
    META[k] = {"mid": mid, "ts": ts, "centres": centres, "trend": trend, "alpha": alpha}

    print(
        f"  k={k:<3} test windows={len(y_true):>6}  "
        f"class balance {np.bincount(y_true, minlength=3) / len(y_true)}  "
        f"mean |trend|={np.abs(trend).mean() * 1e4:.2f} bp"
    )
    _DS_CACHE[k] = (test_ds, y_true, stress)
    return _DS_CACHE[k]


@torch.no_grad()
def evaluate(model, test_ds):
    loader = DataLoader(test_ds, batch_size=BATCH, shuffle=False)
    yt, yp, pr = [], [], []
    for b in loader:
        logits = model.predict(b, DEVICE)
        pr.append(Fn.softmax(logits, dim=1).cpu().numpy())
        yp.append(logits.argmax(dim=1).cpu().numpy())
        yt.append(b["label"].numpy())
    return np.concatenate(yt), np.concatenate(yp), np.concatenate(pr)


# RESULTS[(tag, k)] = {"y_true", "y_pred", "probs", "stress"}
RESULTS: dict = {}

for k in HORIZONS:
    print(f"horizon k={k}")
    try:
        test_ds, y_true, stress = test_set(k)
    except FileNotFoundError as e:
        print(f"  ! could not build test set for k={k}: {e}")
        print(
            f"    (cwd is {Path.cwd()} — if this looks wrong, re-run the setup "
            f"cell; if the file is genuinely missing, run `uv run dvc pull`)"
        )
        continue
    except Exception as e:
        print(f"  ! could not build test set for k={k}: {e}")
        continue
    for tag in MODELS:
        path = CHECKPOINTS.get(tag, {}).get(k)
        if not path or not Path(path).exists():
            print(f"  {DISPLAY[tag]:<24} — no checkpoint, skipped")
            continue
        ckpt = load_ckpt(path)
        cfg = ckpt["config"]
        if cfg.get("label_k") != k or cfg.get("feature_mode") != FEATURE_MODE:
            print(
                f"  {DISPLAY[tag]:<24} ! config mismatch "
                f"(k={cfg.get('label_k')}, fm={cfg.get('feature_mode')}), skipped"
            )
            continue
        model = build_model(tag, ckpt)
        yt, yp, pr = evaluate(model, test_ds)
        assert np.array_equal(yt, y_true), "window/label misalignment"
        RESULTS[(tag, k)] = {"y_true": yt, "y_pred": yp, "probs": pr, "stress": stress}
        acc = (yt == yp).mean()
        f1 = f1_score(yt, yp, average="macro", labels=[0, 1, 2], zero_division=0)
        print(f"  {DISPLAY[tag]:<24} acc={acc:.4f}  macro_f1={f1:.4f}")
        del ckpt, model
        if DEVICE.type == "cuda":
            torch.cuda.empty_cache()

print(f"\nevaluated {len(RESULTS)} (model, horizon) pairs")

"""## 4. Overall metrics"""


def metrics_row(yt, yp):
    per_f1 = f1_score(yt, yp, average=None, labels=[0, 1, 2], zero_division=0)
    return {
        "accuracy": (yt == yp).mean(),
        "macro_f1": f1_score(
            yt, yp, average="macro", labels=[0, 1, 2], zero_division=0
        ),
        "f1_down": per_f1[0],
        "f1_stat": per_f1[1],
        "f1_up": per_f1[2],
    }


rows = []
for (tag, k), r in RESULTS.items():
    rows.append(
        {"model": DISPLAY[tag], "k": k, **metrics_row(r["y_true"], r["y_pred"])}
    )

metrics_df = pd.DataFrame(rows).sort_values(["k", "model"]).reset_index(drop=True)
metrics_df

# accuracy & macro-F1 pivots (rows = model, cols = horizon)
if not metrics_df.empty:
    order = [DISPLAY[m] for m in MODELS if DISPLAY[m] in set(metrics_df["model"])]
    for metric in ["accuracy", "macro_f1"]:
        piv = metrics_df.pivot(index="model", columns="k", values=metric).reindex(order)
        print(f"\n=== {metric} (rows=model, cols=horizon k) ===")
        display(piv.style.background_gradient(cmap="YlGn", axis=None).format("{:.4f}"))

"""### 4b. Dependence-aware paired testing — accuracy and macro-F1

McNemar's test is deliberately not used here: adjacent LOB windows overlap, so
per-window correctness indicators are serially dependent and the usual McNemar
independence assumption would overstate significance. For BTCIRT we instead compare
the diffusion targets against every other model with circular block-bootstrap
confidence intervals. The block length is tied to the horizon and the empirical
autocorrelation time of target correctness. A two-sided bootstrap sign p-value is
reported for the paired difference.
"""

BOOT_TARGETS = ("jumpgatelob", "alphastablelob_1.5")
PAIR_BOOT = 2000
STAT_SEED = 20260802


def _integrated_ac_time_local(x, max_lag=250):
    x = np.asarray(x, dtype=float)
    x = x[np.isfinite(x)]
    if len(x) < 5:
        return 1.0
    x = x - x.mean()
    denom = float(np.dot(x, x))
    if denom <= 1e-24:
        return 1.0
    tau = 1.0
    for lag in range(1, min(max_lag, len(x) - 1) + 1):
        rho = float(np.dot(x[lag:], x[:-lag]) / denom)
        if rho <= 0:
            break
        tau += 2.0 * rho
    return float(max(tau, 1.0))


def _circular_block_indices(n, block, rng):
    block = int(max(1, min(block, n)))
    n_blocks = int(np.ceil(n / block))
    starts = rng.integers(0, n, n_blocks)
    return np.concatenate([(np.arange(s, s + block) % n) for s in starts])[:n]


def _paired_metrics(yt, yp_a, yp_b):
    return {
        "d_acc": float(np.mean(yp_a == yt) - np.mean(yp_b == yt)),
        "d_macro_f1": float(
            f1_score(yt, yp_a, average="macro", labels=[0, 1, 2], zero_division=0)
            - f1_score(yt, yp_b, average="macro", labels=[0, 1, 2], zero_division=0)
        ),
    }


def _paired_block_bootstrap(yt, yp_a, yp_b, block, n_boot=PAIR_BOOT, seed=0):
    yt, yp_a, yp_b = map(np.asarray, (yt, yp_a, yp_b))
    n = len(yt)
    rng = np.random.default_rng(seed)
    vals = {"d_acc": np.empty(n_boot), "d_macro_f1": np.empty(n_boot)}
    for i in range(n_boot):
        idx = _circular_block_indices(n, block, rng)
        m = _paired_metrics(yt[idx], yp_a[idx], yp_b[idx])
        vals["d_acc"][i] = m["d_acc"]
        vals["d_macro_f1"][i] = m["d_macro_f1"]
    out = {}
    for key, arr in vals.items():
        lo, hi = np.percentile(arr, [2.5, 97.5])
        p = 2.0 * min(float(np.mean(arr <= 0.0)), float(np.mean(arr >= 0.0)))
        out[key] = {
            "mean": float(arr.mean()),
            "lo": float(lo),
            "hi": float(hi),
            "p": float(min(1.0, p)),
        }
    return out


boot_targets = [t for t in BOOT_TARGETS if any((t, k) in RESULTS for k in HORIZONS)]
boot_others = [m for m in MODELS if m not in BOOT_TARGETS]

pair_rows = []
for tgt in boot_targets:
    for oth in boot_others:
        for k in HORIZONS:
            if (tgt, k) not in RESULTS or (oth, k) not in RESULTS:
                continue
            rt, ro = RESULTS[(tgt, k)], RESULTS[(oth, k)]
            yt = rt["y_true"]
            if not np.array_equal(yt, ro["y_true"]):
                raise AssertionError(f"{tgt} and {oth} have different y_true for k={k}")
            corr_diff = (rt["y_pred"] == yt).astype(float) - (
                ro["y_pred"] == yt
            ).astype(float)
            block = int(max(k, np.ceil(_integrated_ac_time_local(corr_diff)), 1))
            obs = _paired_metrics(yt, rt["y_pred"], ro["y_pred"])
            boot = _paired_block_bootstrap(
                yt,
                rt["y_pred"],
                ro["y_pred"],
                block,
                seed=STAT_SEED + 17 * k + 1009 * MODEL_INDEX[tgt] + MODEL_INDEX[oth],
            )
            pair_rows.append(
                {
                    "target": DISPLAY[tgt],
                    "vs": DISPLAY[oth],
                    "k": k,
                    "block": block,
                    "d_acc_pp": 100.0 * obs["d_acc"],
                    "d_acc_lo_pp": 100.0 * boot["d_acc"]["lo"],
                    "d_acc_hi_pp": 100.0 * boot["d_acc"]["hi"],
                    "d_acc_p_boot": boot["d_acc"]["p"],
                    "d_f1": obs["d_macro_f1"],
                    "d_f1_lo": boot["d_macro_f1"]["lo"],
                    "d_f1_hi": boot["d_macro_f1"]["hi"],
                    "d_f1_p_boot": boot["d_macro_f1"]["p"],
                }
            )

pair_boot_df = pd.DataFrame(pair_rows)
if pair_boot_df.empty:
    print(
        "No paired bootstrap results — need jumpgatelob/alphastablelob_1.5 in RESULTS."
    )
else:
    order = [DISPLAY[o] for o in boot_others if DISPLAY[o] in set(pair_boot_df["vs"])]
    for tgt in [DISPLAY[t] for t in boot_targets]:
        sub = pair_boot_df[pair_boot_df["target"] == tgt]
        if sub.empty:
            continue
        dacc = sub.pivot(index="vs", columns="k", values="d_acc_pp").reindex(order)
        df1 = sub.pivot(index="vs", columns="k", values="d_f1").reindex(order)
        pval = sub.pivot(index="vs", columns="k", values="d_f1_p_boot").reindex(order)
        print(f"\n=== {tgt} — block-bootstrap paired differences (BTCIRT) ===")
        print(
            "Δaccuracy pp (target − other); block bootstrap handles overlapping windows:"
        )
        display(
            dacc.style.background_gradient(
                cmap="RdYlGn", axis=None, vmin=-5, vmax=5
            ).format("{:+.2f}")
        )
        print("Δmacro-F1 (target − other):")
        display(
            df1.style.background_gradient(
                cmap="RdYlGn", axis=None, vmin=-0.05, vmax=0.05
            ).format("{:+.4f}")
        )
        print("Bootstrap sign p-value for Δmacro-F1:")
        display(
            pval.style.background_gradient(
                cmap="RdYlGn_r", axis=None, vmin=0, vmax=0.1
            ).format("{:.3f}")
        )

"""## 5. Confusion matrices

Row-normalized (recall per true class). One row of panels per horizon.
"""


def plot_confusions(k):
    tags = [t for t in MODELS if (t, k) in RESULTS]
    if not tags:
        return
    fig, axes = plt.subplots(
        1, len(tags), figsize=(3.1 * len(tags), 3.0), squeeze=False
    )
    for ax, tag in zip(axes[0], tags):
        r = RESULTS[(tag, k)]
        cm = confusion_matrix(r["y_true"], r["y_pred"], labels=[0, 1, 2]).astype(float)
        cmn = cm / cm.sum(1, keepdims=True).clip(min=1)
        _ = ax.imshow(cmn, cmap="Blues", vmin=0, vmax=1)
        for i in range(3):
            for j in range(3):
                ax.text(
                    j,
                    i,
                    f"{cmn[i, j]:.2f}",
                    ha="center",
                    va="center",
                    color="white" if cmn[i, j] > 0.5 else "black",
                    fontsize=8,
                )
        ax.set_xticks(range(3), LABELS, rotation=45, ha="right", fontsize=7)
        ax.set_yticks(range(3), LABELS, fontsize=7)
        ax.set_title(DISPLAY[tag], fontsize=8)
        ax.set_xlabel("pred", fontsize=7)
    axes[0][0].set_ylabel("true", fontsize=7)
    fig.suptitle(f"Confusion (row-normalized) — horizon k={k}", y=1.04)
    fig.tight_layout()
    save_fig(fig)
    plt.show()


for k in HORIZONS:
    plot_confusions(k)

"""## 6. Metric vs horizon

How each model's accuracy and macro-F1 evolve as the prediction horizon grows.
"""

if not metrics_df.empty:
    fig, axes = plt.subplots(1, 2, figsize=(12, 4.2))
    cmap = plt.get_cmap("tab10")
    present = [m for m in MODELS if DISPLAY[m] in set(metrics_df["model"])]
    for metric, ax in zip(["accuracy", "macro_f1"], axes):
        for i, tag in enumerate(present):
            sub = metrics_df[metrics_df["model"] == DISPLAY[tag]].sort_values("k")
            ax.plot(sub["k"], sub[metric], "o-", color=cmap(i % 10), label=DISPLAY[tag])
        ax.set_xlabel("horizon k")
        ax.set_ylabel(metric)
        ax.set_title(f"{metric} vs horizon")
        ax.set_xticks(HORIZONS)
        ax.grid(alpha=0.3)
    axes[1].legend(bbox_to_anchor=(1.02, 1), loc="upper left", fontsize=8)
    fig.tight_layout()
    save_fig(fig)
    plt.show()

"""## 7. Extreme conditions (jumps)

Windows are split by their **stress score** (RV-normalized max increment). We
compare performance on **calm** vs **extreme** windows, where *extreme* = the top
`EXTREME_Q` quantile of stress **within each horizon** (guarantees non-empty
buckets). A large `Δ = calm − extreme` means a model degrades under turbulence;
a small Δ means it is jump-robust.
"""

EXTREME_Q = 0.90  # top 10% most turbulent windows = "extreme"


def split_metrics(r, thr):
    st = r["stress"]
    calm, extr = st <= thr, st > thr
    out = {}
    for name, mask in [("calm", calm), ("extreme", extr)]:
        if mask.sum() == 0:
            out[name] = {"n": 0, "accuracy": np.nan, "macro_f1": np.nan}
            continue
        yt, yp = r["y_true"][mask], r["y_pred"][mask]
        out[name] = {
            "n": int(mask.sum()),
            "accuracy": (yt == yp).mean(),
            "macro_f1": f1_score(
                yt, yp, average="macro", labels=[0, 1, 2], zero_division=0
            ),
        }
    return out


rows = []
for (tag, k), r in RESULTS.items():
    thr = np.quantile(r["stress"], EXTREME_Q)
    s = split_metrics(r, thr)
    rows.append(
        {
            "model": DISPLAY[tag],
            "k": k,
            "acc_calm": s["calm"]["accuracy"],
            "acc_extreme": s["extreme"]["accuracy"],
            "f1_calm": s["calm"]["macro_f1"],
            "f1_extreme": s["extreme"]["macro_f1"],
            "f1_drop": s["calm"]["macro_f1"] - s["extreme"]["macro_f1"],
            "n_extreme": s["extreme"]["n"],
        }
    )
extreme_df = pd.DataFrame(rows).sort_values(["k", "model"]).reset_index(drop=True)
extreme_df

# macro-F1 drop under stress (rows=model, cols=horizon) — lower is more robust
if not extreme_df.empty:
    order = [DISPLAY[m] for m in MODELS if DISPLAY[m] in set(extreme_df["model"])]
    piv = extreme_df.pivot(index="model", columns="k", values="f1_drop").reindex(order)
    print("=== macro-F1 drop (calm − extreme); lower = more jump-robust ===")
    display(piv.style.background_gradient(cmap="Reds", axis=None).format("{:.4f}"))

"""### Accuracy vs stress decile

Windows binned into stress deciles; per-model accuracy in each bin. The right side of each panel is the turbulent regime.
"""


def plot_stress_curves(k, n_bins=10):
    tags = [t for t in MODELS if (t, k) in RESULTS]
    if not tags:
        return None
    stress = RESULTS[(tags[0], k)]["stress"]
    edges = np.quantile(stress, np.linspace(0, 1, n_bins + 1))
    edges[-1] += 1e-9
    centers = 0.5 * (edges[:-1] + edges[1:])
    cmap = plt.get_cmap("tab10")
    fig, ax = plt.subplots(figsize=(7, 4))
    for i, tag in enumerate(tags):
        r = RESULTS[(tag, k)]
        correct = (r["y_true"] == r["y_pred"]).astype(float)
        idx = np.clip(np.digitize(r["stress"], edges) - 1, 0, n_bins - 1)
        acc = [
            correct[idx == b].mean() if (idx == b).any() else np.nan
            for b in range(n_bins)
        ]
        ax.plot(centers, acc, "o-", color=cmap(i % 10), label=DISPLAY[tag])
    ax.set_xlabel("window stress (RV units) — decile centers")
    ax.set_ylabel("accuracy")
    ax.set_title(f"Accuracy vs stress — horizon k={k}")
    ax.grid(alpha=0.3)
    ax.legend(fontsize=8)
    fig.tight_layout()
    save_fig(fig)
    plt.show()


for k in HORIZONS:
    plot_stress_curves(k)

"""### Catching the big moves

In the extreme bucket, per-class **recall** for `down` and `up` — does the model still flag large directional moves when they happen?
"""

rows = []
for (tag, k), r in RESULTS.items():
    thr = np.quantile(r["stress"], EXTREME_Q)
    mask = r["stress"] > thr
    if mask.sum() == 0:
        continue
    yt, yp = r["y_true"][mask], r["y_pred"][mask]
    rec = recall_score(yt, yp, average=None, labels=[0, 1, 2], zero_division=0)
    rows.append(
        {"model": DISPLAY[tag], "k": k, "recall_down": rec[0], "recall_up": rec[2]}
    )
recall_df = pd.DataFrame(rows).sort_values(["k", "model"]).reset_index(drop=True)
recall_df

"""## 7b. Financial / trading metrics

Classification scores alone don't say whether signals are *tradeable*. Everything
here is computed against the **realized smoothed trend** `trend_ratio` of each test
window — the exact quantity the ±α labels threshold — so it is a cost-free proxy for
signal quality, **not a trading simulation** (no positions, costs, or fills; that
comes later):

- **MCC & Cohen's κ** — chance-corrected agreement, the headline metrics of recent
  LOB benchmarks (robust to class imbalance, unlike accuracy).
- **Signal rate / directional hit rate** — how often a model calls a direction, and
  the per-signal win rate when it does.
- **Directional capture** — mean signed trend captured per window (bp):
  `+trend` on up-calls, `−trend` on down-calls, `0` on flat.
  `capture_ratio` = captured / oracle (oracle = always right on every window).

"""


def _positions(yp):
    """Predicted position per window: up → +1, down → −1, flat → 0."""
    return np.where(yp == 2, 1, np.where(yp == 0, -1, 0))


fin_rows = []
for (tag, k), r in RESULTS.items():
    m = META.get(k)
    if m is None:
        continue
    yt, yp = r["y_true"], r["y_pred"]
    tr = np.nan_to_num(m["trend"])
    pos = _positions(yp)
    cap = pos * tr
    d = pos != 0
    fin_rows.append(
        {
            "model": DISPLAY[tag],
            "k": k,
            "mcc": matthews_corrcoef(yt, yp),
            "kappa": cohen_kappa_score(yt, yp),
            "signal_rate": d.mean(),
            "hit_rate": (np.sign(tr[d]) == pos[d]).mean() if d.any() else np.nan,
            "capture_bp_win": cap.mean() * 1e4,
            "capture_bp_signal": cap[d].mean() * 1e4 if d.any() else np.nan,
            "oracle_bp_win": np.abs(tr).mean() * 1e4,
            "capture_ratio": cap.mean() / max(np.abs(tr).mean(), 1e-12),
        }
    )
fin_df = pd.DataFrame(fin_rows).sort_values(["k", "model"]).reset_index(drop=True)
fin_df

# MCC and capture-ratio pivots (rows = model, cols = horizon)
if not fin_df.empty:
    order = [DISPLAY[m] for m in MODELS if DISPLAY[m] in set(fin_df["model"])]
    for metric in ["mcc", "capture_ratio", "hit_rate"]:
        piv = fin_df.pivot(index="model", columns="k", values=metric).reindex(order)
        print(f"\n=== {metric} (rows=model, cols=horizon k) ===")
        display(piv.style.background_gradient(cmap="YlGn", axis=None).format("{:.4f}"))

"""### Mid-price path vs model predictions

The mid-price over the most active stretch of the test period, with **true**
up/down regimes shaded (green = up, red = down, white = flat). Each strip below is
one model's predicted label over the same windows — you can see directly *where*
each model catches or misses the moves. Change `seg_len`/`start` to zoom.

"""

LAB_CMAP = ListedColormap(["#d62728", "#e8e8e8", "#2ca02c"])  # down / flat / up


def plot_price_predictions(k, seg_len=600, start=None):
    tags = [t for t in MODELS if (t, k) in RESULTS]
    m = META.get(k)
    if not tags or m is None:
        return
    y_true = RESULTS[(tags[0], k)]["y_true"]
    tr = np.nan_to_num(m["trend"])
    seg_len = min(seg_len, len(y_true))
    if start is None:  # auto-pick the stretch with the most |trend| mass
        act = np.convolve(np.abs(tr), np.ones(seg_len), "valid")
        start = int(act.argmax())
    sl = slice(start, start + seg_len)
    idx = np.arange(start, start + seg_len)
    price = m["mid"][m["centres"][sl]]
    yt_seg = y_true[sl]

    lanes = [("true", yt_seg)] + [
        (DISPLAY[t], RESULTS[(t, k)]["y_pred"][sl]) for t in tags
    ]
    fig, axes = plt.subplots(
        1 + len(lanes),
        1,
        figsize=(12, 3.4 + 0.42 * len(lanes)),
        sharex=True,
        gridspec_kw={"height_ratios": [7] + [1] * len(lanes)},
    )
    ax = axes[0]
    ax.plot(idx, price, lw=0.9, color="black")
    lo, hi = price.min(), price.max()
    pad = 0.03 * (hi - lo + 1e-9)
    ax.fill_between(
        idx,
        lo - pad,
        hi + pad,
        where=yt_seg == 2,
        color="#2ca02c",
        alpha=0.14,
        step="mid",
    )
    ax.fill_between(
        idx,
        lo - pad,
        hi + pad,
        where=yt_seg == 0,
        color="#d62728",
        alpha=0.14,
        step="mid",
    )
    ax.set_ylim(lo - pad, hi + pad)
    ax.set_ylabel("mid")
    ax.set_title(
        f"Mid price with true up/down regimes vs predictions — "
        f"k={k}, windows {start}–{start + seg_len}"
    )
    for axl, (name, lab) in zip(axes[1:], lanes):
        axl.imshow(
            lab[None, :],
            aspect="auto",
            cmap=LAB_CMAP,
            vmin=0,
            vmax=2,
            extent=[idx[0], idx[-1], 0, 1],
            interpolation="nearest",
        )
        axl.set_yticks([])
        axl.set_ylabel(name, rotation=0, ha="right", va="center", fontsize=7)
    axes[-1].set_xlabel("test window (time order)")
    fig.tight_layout(h_pad=0.15)
    save_fig(fig)
    plt.show()


for k in HORIZONS:
    plot_price_predictions(k)


def plot_capture(k):
    tags = [t for t in MODELS if (t, k) in RESULTS]
    m = META.get(k)
    if not tags or m is None:
        return
    tr = np.nan_to_num(m["trend"])
    cmap = plt.get_cmap("tab10")
    fig, ax = plt.subplots(figsize=(10, 4))
    for i, tag in enumerate(tags):
        cap = _positions(RESULTS[(tag, k)]["y_pred"]) * tr
        ax.plot(np.cumsum(cap) * 1e4, color=cmap(i % 10), lw=1.1, label=DISPLAY[tag])
    ax.plot(
        np.cumsum(np.abs(tr)) * 1e4,
        "k--",
        lw=1.0,
        alpha=0.6,
        label="oracle (always right)",
    )
    ax.axhline(0, color="grey", lw=0.6)
    ax.set_xlabel("test window (time order)")
    ax.set_ylabel("cumulative captured trend (bp)")
    ax.set_title(
        f"Cumulative directional capture — k={k} (cost-free, no trading costs)"
    )
    ax.grid(alpha=0.3)
    ax.legend(fontsize=8)
    fig.tight_layout()
    save_fig(fig)
    plt.show()


for k in HORIZONS:
    plot_capture(k)

"""### Calibration & confidence gating

Left — reliability: mean accuracy per confidence decile vs the diagonal (a
calibrated model can be *sized* by its probability). Middle/right — trade only when
`p_max ≥ τ` **and** the call is directional: per-signal hit rate and capture (bp) as
the confidence gate tightens. A model whose hit rate and capture rise with τ gives a
usable filter for the later trading simulation.

"""


def plot_calibration_gating(k, n_bins=10):
    tags = [t for t in MODELS if (t, k) in RESULTS]
    m = META.get(k)
    if not tags or m is None:
        return
    tr = np.nan_to_num(m["trend"])
    taus = np.linspace(0.34, 0.90, 15)
    cmap = plt.get_cmap("tab10")
    fig, axes = plt.subplots(1, 3, figsize=(15, 4))
    for i, tag in enumerate(tags):
        r = RESULTS[(tag, k)]
        conf = r["probs"].max(1)
        correct = (r["y_true"] == r["y_pred"]).astype(float)
        edges = np.quantile(conf, np.linspace(0, 1, n_bins + 1))
        edges[-1] += 1e-9
        bi = np.clip(np.digitize(conf, edges) - 1, 0, n_bins - 1)
        xs = [
            conf[bi == b].mean() if (bi == b).any() else np.nan for b in range(n_bins)
        ]
        ys = [
            correct[bi == b].mean() if (bi == b).any() else np.nan
            for b in range(n_bins)
        ]
        axes[0].plot(xs, ys, "o-", ms=3, color=cmap(i % 10), label=DISPLAY[tag])
        pos = _positions(r["y_pred"])
        hit, cap = [], []
        for tau in taus:
            sel = (pos != 0) & (conf >= tau)
            hit.append((np.sign(tr[sel]) == pos[sel]).mean() if sel.any() else np.nan)
            cap.append((pos[sel] * tr[sel]).mean() * 1e4 if sel.any() else np.nan)
        axes[1].plot(taus, hit, "o-", ms=3, color=cmap(i % 10))
        axes[2].plot(taus, cap, "o-", ms=3, color=cmap(i % 10))
    axes[0].plot([1 / 3, 1], [1 / 3, 1], "k--", lw=0.8, alpha=0.6)
    axes[0].set_xlabel("mean confidence (p_max)")
    axes[0].set_ylabel("accuracy")
    axes[0].set_title(f"Reliability — k={k}")
    axes[0].legend(fontsize=7)
    axes[1].set_xlabel("confidence threshold τ")
    axes[1].set_ylabel("directional hit rate")
    axes[1].set_title("Hit rate vs confidence gate")
    axes[2].set_xlabel("confidence threshold τ")
    axes[2].set_ylabel("capture per signal (bp)")
    axes[2].set_title("Per-signal capture vs confidence gate")
    for ax in axes:
        ax.grid(alpha=0.3)
    fig.tight_layout()
    save_fig(fig)
    plt.show()


for k in HORIZONS:
    plot_calibration_gating(k)

"""## 7c. Robustness to noise injected before feature engineering

This experiment now corrupts the **raw resampled Coinbase rows in the chronological
test region**, rather than adding noise to normalized model tensors. Each corruption
case follows the complete deployed data path:

**held-out raw rows → structurally valid raw perturbation → OFI/features → causal
rolling normalization → regenerated labels and test windows → model accuracy**

Training and validation rows are never changed. Label thresholds are still calibrated
from the untouched training region, while labels are deliberately regenerated from the
perturbed test mid-price, as requested. Consequently, this measures prediction of the
**perturbed market path**; the reported label-change rate shows how different that task
is from the clean test task.

Noise severity is measured in multiples of one-step scales estimated only from training
rows. Price severity uses the standard deviation of training log returns after symmetric
0.5% winsorization (so unchanged 10-second bins cannot collapse the scale); size/count
severity uses MAD-based log-increment scales. A common row-wise log-price shock is applied
to every price field, which
preserves the existing bid/ask ordering. Positive amounts and trade counts are perturbed
in log space and remain non-negative. Mid-price, spread, and trade imbalance are then
recomputed before feature engineering.

The four standardized innovation laws are Gaussian, compound-Poisson/Gamma jump,
Student-t (ν=3), and clipped α-stable. The raw input here is the resampled snapshot
parquet, not the original exchange message stream.

"""

from crypto.dataset import LOBDataset, _valid_starts  # noqa: E402
from crypto.labels import build_labels  # noqa: E402
from crypto.loader import _rolling_mean_std  # noqa: E402
from torch.utils.data import Subset  # noqa: E402

# Full chronological test set by default. Set an integer only for a quick notebook run.
ROBUST_MAX_WINDOWS = None
ROBUST_SIGMAS = [0.0, 0.5, 1.0, 2.0, 4.0]
ROBUST_KINDS = ["gaussian", "jump", "student_t", "alpha_stable"]
SIGMA_FOCUS = 1.0
ROBUST_SEED = 20260802

JUMP = {"rate": 1.0, "shape": 1.0, "scale": 1.0}
STUDENT_NU = 3.0
ASTABLE_ALPHA = 1.7
ASTABLE_CLIP_Q = 0.999


def _robust_std(x, fallback=1.0):
    """MAD-based scale, with an ordinary-std fallback for nearly constant series."""
    x = np.asarray(x, dtype=np.float64)
    x = x[np.isfinite(x)]
    if len(x) == 0:
        return float(fallback)
    med = np.median(x)
    scale = np.median(np.abs(x - med)) / 0.6744897501960817
    if not np.isfinite(scale) or scale < 1e-12:
        scale = np.std(x)
    return float(scale if np.isfinite(scale) and scale >= 1e-12 else fallback)


def _positive_stable(rng, shape, beta):
    """Positive beta-stable draws using Kanter's construction."""
    U = rng.uniform(1e-7, np.pi - 1e-7, size=shape)
    E = np.maximum(rng.exponential(size=shape), 1e-12)
    term1 = np.sin(beta * U) / np.maximum(np.sin(U), 1e-12) ** (1.0 / beta)
    term2 = np.maximum(np.sin((1.0 - beta) * U) / E, 1e-30) ** ((1.0 - beta) / beta)
    return np.maximum(term1 * term2, 1e-12)


# A single fixed truncation and normalization, not a batch-dependent test statistic.
_cap_rng = np.random.default_rng(ROBUST_SEED)
_cap_draw = _positive_stable(_cap_rng, 250_000, beta=ASTABLE_ALPHA / 2.0)
ASTABLE_CAP = float(np.quantile(_cap_draw, ASTABLE_CLIP_Q))
ASTABLE_STD = float(np.sqrt(np.mean(np.minimum(_cap_draw, ASTABLE_CAP))))


def _unit_innovations(rng, shape, kind):
    """Zero-centred, approximately unit-variance innovations for fair severity."""
    if kind == "gaussian":
        return rng.standard_normal(shape)
    if kind == "student_t":
        return rng.standard_t(STUDENT_NU, size=shape) * np.sqrt(
            (STUDENT_NU - 2.0) / STUDENT_NU
        )
    if kind == "jump":
        count = rng.poisson(JUMP["rate"], size=shape)
        jump_var = np.zeros(shape, dtype=np.float64)
        mask = count > 0
        if np.any(mask):
            jump_var[mask] = rng.gamma(count[mask] * JUMP["shape"], JUMP["scale"])
        total_var = 1.0 + jump_var
        expected_var = 1.0 + JUMP["rate"] * JUMP["shape"] * JUMP["scale"]
        return rng.standard_normal(shape) * np.sqrt(total_var / expected_var)
    if kind == "alpha_stable":
        A = _positive_stable(rng, shape, beta=ASTABLE_ALPHA / 2.0)
        A = np.minimum(A, ASTABLE_CAP)
        return rng.standard_normal(shape) * np.sqrt(A) / ASTABLE_STD
    raise ValueError(f"unknown corruption kind {kind!r}")


# Load the resampled raw snapshot table once. Splits exactly match build_datasets().
_RAW_CFG = json.loads(
    (REPO / DATA_CONFIG.format(fm=FEATURE_MODE, k=HORIZONS[0])).read_text()
)
_RAW_PATH = REPO / _RAW_CFG["data_dir"] / f"{SYMBOL}.parquet.gz"
_RAW_DF = pd.read_parquet(_RAW_PATH).sort_values("timestamp_utc").reset_index(drop=True)
_RAW_DF["_date"] = _RAW_DF["timestamp_utc"].dt.date
_RAW_N = len(_RAW_DF)
_RAW_TRAIN_END = int(_RAW_N * _RAW_CFG["train_frac"])
_RAW_TEST_START = int(_RAW_N * (_RAW_CFG["train_frac"] + _RAW_CFG["val_frac"]))
_RAW_TS = _RAW_DF["bin"].to_numpy(np.int64)

_RAW_PRICE_COLS = [
    c for c in _RAW_DF.columns if c.endswith(".price") or c in {"mid", "vwap"}
]
_RAW_SIZE_COLS = [
    c for c in _RAW_DF.columns if c.endswith(".amount") or c in {"buy_vol", "sell_vol"}
]

_train_mid = _RAW_DF["mid"].to_numpy(np.float64)[:_RAW_TRAIN_END]
_train_log_return = np.diff(np.log(np.maximum(_train_mid, 1e-12)))
_price_lo, _price_hi = np.quantile(_train_log_return, [0.005, 0.995])
RAW_PRICE_STEP = float(np.std(np.clip(_train_log_return, _price_lo, _price_hi)))
if not np.isfinite(RAW_PRICE_STEP) or RAW_PRICE_STEP < 1e-12:
    RAW_PRICE_STEP = _robust_std(_train_log_return)

RAW_SIZE_STEP = {}
for _c in _RAW_SIZE_COLS:
    _v = np.maximum(
        pd.to_numeric(_RAW_DF[_c], errors="coerce").to_numpy(np.float64)[
            :_RAW_TRAIN_END
        ],
        0.0,
    )
    RAW_SIZE_STEP[_c] = _robust_std(np.diff(np.log1p(_v)), fallback=0.1)

_count_train = np.maximum(
    pd.to_numeric(_RAW_DF["trade_count"], errors="coerce").to_numpy(np.float64)[
        :_RAW_TRAIN_END
    ],
    0.0,
)
RAW_COUNT_STEP = _robust_std(np.diff(np.log1p(_count_train)), fallback=0.1)

print(
    f"raw rows={_RAW_N:,}; test starts at row {_RAW_TEST_START:,}; "
    f"price-step scale={RAW_PRICE_STEP:.3e}; "
    f"median amount-step scale={np.median(list(RAW_SIZE_STEP.values())):.3f}"
)


def _corrupt_test_rows(kind, sigma):
    """Copy raw data and perturb only rows belonging to the held-out test region."""
    df = _RAW_DF.copy()
    if sigma == 0.0:
        return df

    seed = ROBUST_SEED + 100_003 * ROBUST_KINDS.index(kind) + int(round(10_000 * sigma))
    rng = np.random.default_rng(seed)
    n_test = _RAW_N - _RAW_TEST_START
    test_slice = slice(_RAW_TEST_START, _RAW_N)

    # One price shock per timestamp, shared by every price level/field. This keeps
    # the original book ordering and relative tick geometry intact.
    price_z = _unit_innovations(rng, n_test, kind)
    log_price_shock = sigma * RAW_PRICE_STEP * price_z
    log_price_shock = np.clip(log_price_shock, -0.25, 0.25)
    price_factor = np.exp(log_price_shock)
    for col in _RAW_PRICE_COLS:
        values = pd.to_numeric(df[col], errors="coerce").to_numpy(np.float64)
        values[test_slice] = values[test_slice] * price_factor
        df[col] = values

    # Sizes remain non-negative. Structural zeros remain zero rather than becoming
    # artificial orders/trades.
    for col in _RAW_SIZE_COLS:
        values = pd.to_numeric(df[col], errors="coerce").to_numpy(np.float64)
        current = values[test_slice].copy()
        positive = np.isfinite(current) & (current > 0.0)
        z = _unit_innovations(rng, n_test, kind)
        log_value = np.log1p(np.maximum(current[positive], 0.0))
        log_value = np.maximum(
            log_value + sigma * RAW_SIZE_STEP[col] * z[positive], 0.0
        )
        current[positive] = np.expm1(np.minimum(log_value, 30.0))
        values[test_slice] = current
        df[col] = values

    count = pd.to_numeric(df["trade_count"], errors="coerce").to_numpy(np.float64)
    current = count[test_slice].copy()
    positive = np.isfinite(current) & (current > 0.0)
    z = _unit_innovations(rng, n_test, kind)
    log_count = np.log1p(np.maximum(current[positive], 0.0))
    log_count = np.maximum(log_count + sigma * RAW_COUNT_STEP * z[positive], 0.0)
    current[positive] = np.rint(np.expm1(np.minimum(log_count, 20.0)))
    count[test_slice] = current
    df["trade_count"] = count

    # Rebuild dependent raw fields before feature and label construction.
    bid0 = df["bids[0].price"].to_numpy(np.float64)
    ask0 = df["asks[0].price"].to_numpy(np.float64)
    df["mid"] = (bid0 + ask0) / 2.0
    df["spread"] = ask0 - bid0
    buy = np.maximum(df["buy_vol"].to_numpy(np.float64), 0.0)
    sell = np.maximum(df["sell_vol"].to_numpy(np.float64), 0.0)
    df["trade_imbalance"] = (buy - sell) / (buy + sell + 1e-12)
    return df


def _test_features_from_raw(df, cfg):
    """Recompute raw OFI/features and exact causal normalization for test rows."""
    norm_window = int(cfg.get("norm_window", 2000))

    # One preceding row is needed to compute OFI/returns correctly at the start of
    # the normalization context. It is discarded before rolling statistics.
    context_lo = max(0, _RAW_TEST_START - norm_window)
    extract_lo = max(0, context_lo - 1)
    tail = df.iloc[extract_lo:].copy()

    blocks = []
    for _, day_df in tail.groupby("_date", sort=True):
        blocks.append(extract_features(day_df.reset_index(drop=True), cfg))
    raw_ext = np.concatenate(blocks, axis=0).astype(np.float64)
    raw_context = raw_ext[context_lo - extract_lo :]

    mean, std, count = _rolling_mean_std(raw_context, norm_window)
    std = np.where((count < 2) | (std < 1e-8), 1.0, std)
    normalized = ((raw_context - mean) / std).astype(np.float32)
    test_offset = _RAW_TEST_START - context_lo
    return normalized[test_offset:]


_RAW_CASE_CACHE = {}


def _raw_case(kind, sigma):
    """Return corrupted test features and full mid path, cached across horizons."""
    key = ("clean", 0.0) if sigma == 0.0 else (kind, float(sigma))
    if key not in _RAW_CASE_CACHE:
        noisy = _corrupt_test_rows(kind, sigma)
        _RAW_CASE_CACHE[key] = {
            "features": _test_features_from_raw(noisy, _RAW_CFG),
            "mid": noisy["mid"].to_numpy(np.float64),
        }
    return _RAW_CASE_CACHE[key]


def _case_distortion(kind, sigma):
    """Measured distortion on normalized test features, comparable across laws."""
    clean = _raw_case("gaussian", 0.0)["features"].astype(np.float64)
    noisy = _raw_case(kind, sigma)["features"].astype(np.float64)
    delta = noisy - clean
    rel_l2 = np.linalg.norm(delta) / max(np.linalg.norm(clean), 1e-12)
    clean_mad = np.median(
        np.abs(clean - np.median(clean, axis=0, keepdims=True)), axis=0
    )
    delta_mad = np.median(np.abs(delta), axis=0)
    mad_ratio = np.nanmedian(delta_mad / np.maximum(clean_mad, 1e-12))
    q_clean = np.nanquantile(np.abs(clean), 0.95, axis=0)
    q_delta = np.nanquantile(np.abs(delta), 0.95, axis=0)
    q95_ratio = np.nanmedian(q_delta / np.maximum(q_clean, 1e-12))
    abnormal_move_prob = float(
        np.mean(np.abs(delta) > np.nanquantile(np.abs(clean), 0.99))
    )
    return {
        "distortion_l2": float(rel_l2),
        "distortion_mad": float(mad_ratio),
        "distortion_q95": float(q95_ratio),
        "abnormal_move_prob": abnormal_move_prob,
    }


def raw_test_set(k, kind, sigma):
    """Build a test dataset after raw corruption, feature extraction, and labeling."""
    cfg = json.loads((REPO / DATA_CONFIG.format(fm=FEATURE_MODE, k=k)).read_text())
    case = _raw_case(kind, sigma)
    labels, alpha = build_labels(case["mid"], cfg, _RAW_TRAIN_END)
    starts = _valid_starts(
        _RAW_TEST_START,
        _RAW_N,
        cfg["T_past"],
        cfg["label_k"],
        labels,
        _RAW_TS,
        cfg["stride"],
    )
    starts_rel = starts - _RAW_TEST_START
    labels_test = labels[_RAW_TEST_START:]
    ds = LOBDataset(case["features"], starts_rel, labels_test, cfg["T_past"])
    y = labels[starts + cfg["T_past"] - 1]
    return ds, y, {"alpha": alpha, "starts": starts}


"""### 7d. Real market stress tests

Synthetic corruption is only one robustness view. This table uses the uncorrupted
BTCIRT test period and slices windows by observed market stress regimes: high
realized volatility, spread widening, liquidity drops, abnormal OFI bursts, and
timestamp gaps that proxy exchange/data outages. Each regime is selected from the
top or bottom decile within the same horizon, except exchange gaps, which are
reported only where a real gap is present.
"""


def _window_apply(starts, width, values, func):
    values = np.asarray(values, dtype=np.float64)
    return np.asarray([func(values[s : s + width]) for s in starts], dtype=np.float64)


def _real_stress_scores(k):
    cfg = json.loads((REPO / DATA_CONFIG.format(fm=FEATURE_MODE, k=k)).read_text())
    _, y, meta = raw_test_set(k, "gaussian", 0.0)
    starts = meta["starts"]
    width = int(cfg["T_past"])

    mid = np.maximum(_RAW_DF["mid"].to_numpy(np.float64), 1e-12)
    log_mid = np.log(mid)
    spread = np.maximum(_RAW_DF["spread"].to_numpy(np.float64), 0.0) / mid

    bid_amt = _RAW_DF.get("bids[0].amount", pd.Series(0.0, index=_RAW_DF.index))
    ask_amt = _RAW_DF.get("asks[0].amount", pd.Series(0.0, index=_RAW_DF.index))
    top_depth = np.maximum(
        pd.to_numeric(bid_amt, errors="coerce").to_numpy(np.float64), 0.0
    ) + np.maximum(pd.to_numeric(ask_amt, errors="coerce").to_numpy(np.float64), 0.0)

    buy = np.maximum(_RAW_DF["buy_vol"].to_numpy(np.float64), 0.0)
    sell = np.maximum(_RAW_DF["sell_vol"].to_numpy(np.float64), 0.0)
    ofi_burst = np.abs(buy - sell) / (buy + sell + 1e-12)

    ts = _RAW_DF["bin"].to_numpy(np.int64)
    dt = np.diff(ts, prepend=ts[0])
    ordinary_dt = np.median(dt[dt > 0]) if np.any(dt > 0) else 0

    scores = {
        "high_volatility": _window_apply(
            starts, width + 1, log_mid, lambda x: np.std(np.diff(x))
        ),
        "spread_widening": _window_apply(starts, width, spread, np.nanmean),
        "liquidity_drop": -_window_apply(starts, width, top_depth, np.nanmean),
        "abnormal_ofi_burst": _window_apply(starts, width, ofi_burst, np.nanmax),
    }
    if ordinary_dt > 0:
        scores["exchange_gap"] = _window_apply(
            starts, width, dt, lambda x: np.max(x) > 1.5 * ordinary_dt
        )
    else:
        scores["exchange_gap"] = np.zeros(len(starts), dtype=bool)
    return y, scores


def _mask_from_score(score, q=0.90):
    score = np.asarray(score)
    if score.dtype == bool:
        return score
    finite = np.isfinite(score)
    if not np.any(finite):
        return np.zeros(len(score), dtype=bool)
    thr = np.quantile(score[finite], q)
    return finite & (score >= thr)


real_stress_rows = []
for k in HORIZONS:
    if not any((tag, k) in RESULTS for tag in MODELS):
        continue
    y_clean, score_map = _real_stress_scores(k)
    for condition, score in score_map.items():
        mask = _mask_from_score(score)
        if mask.sum() == 0:
            real_stress_rows.append(
                {
                    "condition": condition,
                    "model": "(no real events)",
                    "k": k,
                    "n": 0,
                    "accuracy": np.nan,
                    "macro_f1": np.nan,
                }
            )
            continue
        for tag in MODELS:
            if (tag, k) not in RESULTS:
                continue
            r = RESULTS[(tag, k)]
            if not np.array_equal(r["y_true"], y_clean):
                raise AssertionError(f"real-stress labels differ for {tag}, k={k}")
            yt, yp = r["y_true"][mask], r["y_pred"][mask]
            real_stress_rows.append(
                {
                    "condition": condition,
                    "model": DISPLAY[tag],
                    "k": k,
                    "n": int(mask.sum()),
                    "accuracy": float(np.mean(yt == yp)),
                    "macro_f1": f1_score(
                        yt,
                        yp,
                        average="macro",
                        labels=[0, 1, 2],
                        zero_division=0,
                    ),
                }
            )

real_stress_df = pd.DataFrame(real_stress_rows)
if not real_stress_df.empty:
    display(real_stress_df.sort_values(["condition", "k", "model"]))
    for metric in ["accuracy", "macro_f1"]:
        print(f"\n=== real market stress {metric} (mean across horizons) ===")
        piv = real_stress_df.pivot_table(
            index="model", columns="condition", values=metric, aggfunc="mean"
        )
        order = [DISPLAY[m] for m in MODELS if DISPLAY[m] in set(piv.index)]
        display(
            piv.reindex(order)
            .style.background_gradient(cmap="YlGn", axis=None)
            .format("{:.4f}")
        )


def _select_test_subset(ds, y, k):
    """Use every test window unless ROBUST_MAX_WINDOWS explicitly requests a cap."""
    if ROBUST_MAX_WINDOWS is None or len(ds) <= ROBUST_MAX_WINDOWS:
        return ds, y
    rng = np.random.default_rng(ROBUST_SEED + k)
    idx = np.sort(rng.choice(len(ds), ROBUST_MAX_WINDOWS, replace=False))
    return Subset(ds, idx.tolist()), y[idx]


@torch.no_grad()
def run_raw_robust_sweep():
    """Accuracy/F1 after raw corruption; keep jump-case probabilities for calibration."""
    rows, probs = [], {}

    for k in HORIZONS:
        cases = {}
        clean_ds, clean_y, clean_meta = raw_test_set(k, "gaussian", 0.0)
        clean_ds, clean_y = _select_test_subset(clean_ds, clean_y, k)

        # Verify that rebuilding the untouched raw path reproduces test labels.
        _, reference_y, _ = test_set(k)
        if ROBUST_MAX_WINDOWS is None:
            if not np.array_equal(clean_y, reference_y):
                raise AssertionError(f"k={k}: raw clean labels do not match test_set()")
        print(f"k={k}: prepared {len(clean_y):,} chronological test windows")

        for kind in ROBUST_KINDS:
            for sigma in ROBUST_SIGMAS:
                ds, y, meta = raw_test_set(k, kind, sigma)
                ds, y = _select_test_subset(ds, y, k)
                if len(y) != len(clean_y):
                    raise AssertionError(
                        f"k={k}, {kind}, sigma={sigma}: test-window count changed"
                    )
                cases[(kind, sigma)] = (
                    ds,
                    y,
                    float(np.mean(y != clean_y)),
                    _case_distortion(kind, sigma),
                )

        for tag in MODELS:
            path = CHECKPOINTS.get(tag, {}).get(k)
            if not path or not Path(path).exists():
                continue
            model = build_model(tag, load_ckpt(path))
            prediction_cache = {}

            for kind in ROBUST_KINDS:
                for sigma in ROBUST_SIGMAS:
                    cache_key = ("clean", 0.0) if sigma == 0.0 else (kind, sigma)
                    ds, expected_y, label_change, distortion = cases[(kind, sigma)]
                    if cache_key not in prediction_cache:
                        prediction_cache[cache_key] = evaluate(model, ds)
                    yt, yp, pr = prediction_cache[cache_key]
                    if not np.array_equal(yt, expected_y):
                        raise AssertionError(
                            "dataset labels and evaluation labels differ"
                        )

                    rows.append(
                        {
                            "model": DISPLAY[tag],
                            "k": k,
                            "kind": kind,
                            "sigma": sigma,
                            **distortion,
                            "accuracy": float(np.mean(yt == yp)),
                            "macro_f1": f1_score(
                                yt,
                                yp,
                                average="macro",
                                labels=[0, 1, 2],
                                zero_division=0,
                            ),
                            "label_change_rate": label_change,
                        }
                    )
                    if kind == "jump" and abs(sigma - SIGMA_FOCUS) < 1e-12:
                        probs[(tag, k)] = (yt, yp, pr)

            del model
            if DEVICE.type == "cuda":
                torch.cuda.empty_cache()

        n_models = len({r["model"] for r in rows if r["k"] == k})
        print(f"  evaluated {n_models} models")

    return pd.DataFrame(rows), probs


scope = (
    "full test set" if ROBUST_MAX_WINDOWS is None else f"{ROBUST_MAX_WINDOWS} windows"
)
print(
    f"running raw-data noise sweep on {scope}: "
    f"{len(ROBUST_SIGMAS)} severities × {len(ROBUST_KINDS)} laws"
)
robust_df, ROBUST_PROBS = run_raw_robust_sweep()
print(f"done — {len(robust_df)} metric rows")
robust_df.head()


# Accuracy vs raw-data noise severity — one figure per prediction horizon.
def plot_robust_sweep(k):
    if robust_df.empty or "k" not in robust_df.columns:
        return
    sub = robust_df[robust_df["k"] == k]
    if sub.empty:
        return

    cmap = plt.get_cmap("tab10")
    present = [DISPLAY[m] for m in MODELS if DISPLAY[m] in set(sub["model"])]
    n = len(ROBUST_KINDS)
    fig, axes = plt.subplots(1, n, figsize=(3.7 * n, 4.4), sharey=True)
    axes = np.atleast_1d(axes)

    for ax, kind in zip(axes, ROBUST_KINDS):
        data = sub[sub["kind"] == kind]
        for i, name in enumerate(present):
            model_rows = data[data["model"] == name].sort_values("distortion_l2")
            ax.plot(
                model_rows["distortion_l2"],
                model_rows["accuracy"],
                "o-",
                ms=4,
                color=cmap(i % 10),
                label=name,
            )
        ax.set_xlabel(r"measured distortion $\|x'-x\|_2 / \|x\|_2$")
        ax.set_title(f"{kind} innovations")
        ax.grid(alpha=0.3)

    axes[0].set_ylabel("test accuracy (regenerated labels)")
    axes[-1].legend(bbox_to_anchor=(1.02, 1), loc="upper left", fontsize=8)
    fig.suptitle(
        f"Raw-data corruption robustness — horizon k={k}",
        y=1.03,
    )
    fig.tight_layout()
    save_fig(fig)
    plt.show()


for k in HORIZONS:
    plot_robust_sweep(k)


# Accuracy retention at the strongest raw corruption; higher is better.
if not robust_df.empty:
    high = robust_df["sigma"].max()
    base = (
        robust_df[robust_df["sigma"] == 0.0]
        .groupby(["model", "kind"])["accuracy"]
        .mean()
    )
    top = (
        robust_df[robust_df["sigma"] == high]
        .groupby(["model", "kind"])["accuracy"]
        .mean()
    )
    retention = (top / base.clip(lower=1e-9)).rename("retention").reset_index()
    order = [DISPLAY[m] for m in MODELS if DISPLAY[m] in set(retention["model"])]
    pivot = retention.pivot(index="model", columns="kind", values="retention").reindex(
        order
    )
    pivot = pivot[[kind for kind in ROBUST_KINDS if kind in pivot.columns]]
    pivot["mean"] = pivot.mean(axis=1)
    print(f"\nAccuracy retention at strongest requested corruption (sigma={high}):")
    display(
        pivot.sort_values("mean", ascending=False)
        .style.background_gradient(cmap="YlGn", axis=None)
        .format("{:.3f}")
    )

    label_drift = (
        robust_df[
            [
                "k",
                "kind",
                "sigma",
                "distortion_l2",
                "distortion_mad",
                "distortion_q95",
                "abnormal_move_prob",
                "label_change_rate",
            ]
        ]
        .drop_duplicates()
        .pivot_table(
            index=[
                "kind",
                "sigma",
                "distortion_l2",
                "distortion_mad",
                "distortion_q95",
                "abnormal_move_prob",
            ],
            columns="k",
            values="label_change_rate",
        )
    )
    print(
        "\nFraction of regenerated test labels that differ from clean labels "
        "(this quantifies task drift):"
    )
    display(label_drift.style.format("{:.2%}"))

"""### Calibration under raw jump corruption

Reliability curves use the raw-data **jump** case at severity
`SIGMA_FOCUS`, after reconstructing features and labels through the same pipeline.
They therefore assess confidence on the perturbed test path, not on tensor-level noise.

"""


def plot_calibration_under_noise(k, n_bins=10):
    tags = [tag for tag in MODELS if (tag, k) in ROBUST_PROBS]
    if not tags:
        return

    cmap = plt.get_cmap("tab10")
    fig, ax = plt.subplots(figsize=(6.2, 5))
    for i, tag in enumerate(tags):
        yt, yp, probabilities = ROBUST_PROBS[(tag, k)]
        confidence = probabilities.max(1)
        correct = (yt == yp).astype(float)
        edges = np.quantile(confidence, np.linspace(0, 1, n_bins + 1))
        edges[-1] += 1e-9
        bin_id = np.clip(np.digitize(confidence, edges) - 1, 0, n_bins - 1)
        mean_confidence = [
            confidence[bin_id == b].mean() if np.any(bin_id == b) else np.nan
            for b in range(n_bins)
        ]
        mean_accuracy = [
            correct[bin_id == b].mean() if np.any(bin_id == b) else np.nan
            for b in range(n_bins)
        ]
        ece = np.nansum(
            [
                np.mean(bin_id == b)
                * abs(
                    np.nan_to_num(mean_accuracy[b]) - np.nan_to_num(mean_confidence[b])
                )
                for b in range(n_bins)
            ]
        )
        ax.plot(
            mean_confidence,
            mean_accuracy,
            "o-",
            ms=4,
            color=cmap(i % 10),
            label=f"{DISPLAY[tag]} (ECE={ece:.3f})",
        )

    ax.plot([1 / 3, 1], [1 / 3, 1], "k--", lw=0.8, alpha=0.6)
    ax.set_xlabel("mean confidence (p_max)")
    ax.set_ylabel("accuracy")
    jump_d = _case_distortion("jump", SIGMA_FOCUS)["distortion_l2"]
    ax.set_title(f"Reliability after raw jump corruption (D={jump_d:.3f}) — k={k}")
    ax.legend(fontsize=7)
    ax.grid(alpha=0.3)
    fig.tight_layout()
    save_fig(fig)
    plt.show()


for k in HORIZONS:
    plot_calibration_under_noise(k)

"""### Bootstrap confidence intervals on macro-F1

The test set is short (~22 days, one asset), so small macro-F1 gaps may be noise. We
resample the **clean** test windows in circular blocks and report the 95% interval
per model. Block resampling keeps overlapping-window dependence in the uncertainty
estimate. Overlapping intervals ⇒ the models are statistically indistinguishable.

"""


def block_bootstrap_f1(yt, yp, block, n=1000, seed=0):
    rng = np.random.default_rng(seed)
    N = len(yt)
    vals = np.empty(n)
    for i in range(n):
        idx = _circular_block_indices(N, block, rng)
        vals[i] = f1_score(
            yt[idx], yp[idx], average="macro", labels=[0, 1, 2], zero_division=0
        )
    return vals.mean(), np.percentile(vals, 2.5), np.percentile(vals, 97.5)


boot_rows = []
for (tag, k), r in RESULTS.items():
    correct = (r["y_true"] == r["y_pred"]).astype(float)
    block = int(max(k, np.ceil(_integrated_ac_time_local(correct)), 1))
    mean, lo, hi = block_bootstrap_f1(
        r["y_true"],
        r["y_pred"],
        block,
        seed=STAT_SEED + 31 * k + MODEL_INDEX[tag],
    )
    boot_rows.append(
        {
            "model": DISPLAY[tag],
            "k": k,
            "block": block,
            "mean": mean,
            "lo": lo,
            "hi": hi,
            "pm": 0.5 * (hi - lo),
        }
    )
boot_df = pd.DataFrame(boot_rows)

# forest plot: macro-F1 ± 95% CI per model, one panel per horizon
present = [DISPLAY[m] for m in MODELS if DISPLAY[m] in set(boot_df["model"])]
fig, axes = plt.subplots(
    1, len(HORIZONS), figsize=(4 * len(HORIZONS), 3.6), sharey=True
)
axes = np.atleast_1d(axes)
cmap = plt.get_cmap("tab10")
for ax, k in zip(axes, HORIZONS):
    d = boot_df[boot_df["k"] == k].set_index("model").reindex(present).dropna()
    y = np.arange(len(d))
    ax.errorbar(
        d["mean"],
        y,
        xerr=[d["mean"] - d["lo"], d["hi"] - d["mean"]],
        fmt="o",
        color="black",
        ecolor="grey",
        capsize=3,
        ms=5,
    )
    ax.set_yticks(y, d.index if k == HORIZONS[0] else [""] * len(d), fontsize=8)
    ax.set_title(f"k={k}")
    ax.set_xlabel("macro-F1 (95% CI)")
    ax.grid(alpha=0.3, axis="x")
fig.suptitle(
    "Bootstrap 95% CI on macro-F1 — overlapping bars = indistinguishable", y=1.03
)
fig.tight_layout()
save_fig(fig)
plt.show()
display(
    boot_df.pivot(index="model", columns="k", values="mean")
    .reindex(present)
    .style.format("{:.4f}")
)
display(
    boot_df.pivot(index="model", columns="k", values="pm")
    .reindex(present)
    .style.format("±{:.4f}")
)

"""## 8. Final model comparison table

Mean macro-F1 across horizons (overall, calm, extreme) plus the financial
aggregates (mean MCC / capture ratio). `robustness` = extreme / calm.

"""

if RESULTS:
    agg = metrics_df.groupby("model")["macro_f1"].mean().rename("macro_f1_mean")
    parts = [agg]
    if not fin_df.empty:
        parts.append(fin_df.groupby("model")[["mcc", "capture_ratio"]].mean())
    ex = extreme_df.groupby("model")[["f1_calm", "f1_extreme"]].mean()
    parts.append(ex)
    summary = pd.concat(parts, axis=1)
    summary["robustness"] = summary["f1_extreme"] / summary["f1_calm"].clip(lower=1e-9)
    summary = summary.sort_values("macro_f1_mean", ascending=False)
    grad_cols = [
        c
        for c in ["macro_f1_mean", "mcc", "capture_ratio", "f1_calm", "f1_extreme"]
        if c in summary.columns
    ]
    display(
        summary.style.background_gradient(cmap="YlGn", subset=grad_cols).format(
            "{:.4f}"
        )
    )
else:
    print("No results — populate CHECKPOINTS in section 2 and re-run.")

"""### 9.0 Config"""

# Global knobs for the significance battery. It runs on EVERY (model, horizon)
# in RESULTS — no single target to pick.
H_FWD = None  # forward-return horizon in *windows*; None -> that pair's k
FLAT_THRESHOLD = 0.0  # |score| <= thr counts as "no directional call"
COST_BPS = 5.0  # round-trip cost: half-spread + fees + adverse selection
N_BOOT = 2000  # block-bootstrap resamples
CI = 0.95  # two-sided bootstrap coverage
MEAN_BURN = 250  # burn-in windows before the prevailing mean is trusted
RHO_GRID = [0.0, 0.5, 0.9, 0.95, 0.99]  # AR(1) values swept for breadth deflation
N_REL_BINS = 10  # reliability-diagram / Murphy bins
REL_FOCUS_K = None  # horizon for the reliability-diagram panel; None -> first
print(
    f"significance battery over {len(RESULTS)} (model, horizon) pairs, cost={COST_BPS}bp"
)

"""### 9.1 Data-loading stub

`build_eval_frame` assembles the per-decision-point dataframe the tests consume,
straight from this notebook's `RESULTS`/`META`. Columns match the spec:
`ts, score, pred_class, p_down/p_flat/p_up, r_hat, r_fwd, cost`, plus the two
baselines `r_mean` (prevailing-mean, *nested*) and `r_rw` (persistence,
*non-nested*). **To score an external model**, replace the body of this function
with your own dataframe — the rest of the section only touches these columns.
"""

from scipy import stats  # noqa: E402


def _forward_return(mid, centres, h):
    """Log forward mid return over h windows; NaN where the horizon runs off the end."""
    mid = np.asarray(mid, float)
    nxt = centres + h
    ok = nxt < len(mid)
    r = np.full(len(centres), np.nan)
    r[ok] = np.log(mid[nxt[ok]]) - np.log(mid[centres[ok]])
    return r


def build_eval_frame(tag, k, h=None, flat_thr=0.0, cost_bps=COST_BPS):
    """Per-decision-point frame for (tag, k). See section header for column spec.

    r_hat: these are *classifiers* with no native return forecast, so the score
    s = P(up)-P(down) is mapped to return units by a single fixed scale matched to
    the realized-return dispersion (monotone, in-sample). Drop in a genuine model
    point-forecast here if you have one.
    """
    r, m = RESULTS[(tag, k)], META[k]
    h = k if h is None else h
    pr = r["probs"]
    score = pr[:, 2] - pr[:, 0]
    r_fwd = _forward_return(m["mid"], m["centres"], h)
    ss, sr = np.nanstd(score), np.nanstd(r_fwd)
    r_hat = score * (sr / ss if ss > 0 else 0.0)
    ts = np.asarray(m["ts"])[m["centres"]] if "ts" in m else np.arange(len(score))
    df = pd.DataFrame(
        {
            "ts": ts,
            "score": score,
            "pred_class": r["y_pred"],
            "p_down": pr[:, 0],
            "p_flat": pr[:, 1],
            "p_up": pr[:, 2],
            "r_hat": r_hat,
            "r_fwd": r_fwd,
            "cost": cost_bps / 1e4,
        }
    )
    # nested baseline: expanding (out-of-sample) prevailing mean of r_fwd
    rf = df["r_fwd"].to_numpy()
    csum = np.nancumsum(rf)
    cnt = np.cumsum(~np.isnan(rf))
    prev = np.full(len(rf), np.nan)
    prev[1:] = csum[:-1] / np.clip(cnt[:-1], 1, None)
    prev[cnt < MEAN_BURN] = np.nan
    df["r_mean"] = prev
    # non-nested baseline: persistence (previous window's realized fwd return)
    df["r_rw"] = df["r_fwd"].shift(1)
    df["dir_call"] = np.where(
        np.abs(df["score"]) <= flat_thr, 0, np.sign(df["score"])
    ).astype(int)
    return df


def integrated_ac_time(x, max_lag=200):
    """Integrated autocorr time tau = 1 + 2*sum_{l>=1} rho_l (positive part, Sokal).

    Ties the HAC lag and the bootstrap block length to the signal's own memory.
    """
    x = np.asarray(x, float)
    x = x[~np.isnan(x)]
    x = x - x.mean()
    n = len(x)
    denom = np.dot(x, x)
    if denom <= 0 or n < 5:
        return 1.0
    tau, max_lag = 1.0, min(max_lag, n - 1)
    for lag in range(1, max_lag + 1):
        rho = np.dot(x[lag:], x[:-lag]) / denom
        if rho <= 0:  # stop at first non-positive lag
            break
        tau += 2 * rho
    return float(max(tau, 1.0))


# Build one eval frame per (model, horizon), plus its own HAC lag / block length
# (each series gets a lag tied to ITS autocorrelation time and forward horizon).
FRAMES, HACP = {}, {}
for tag, k in RESULTS:
    if META.get(k) is None:
        continue
    fr = build_eval_frame(tag, k, H_FWD, FLAT_THRESHOLD, COST_BPS)
    h_eff = k if H_FWD is None else H_FWD
    ac = int(np.ceil(integrated_ac_time(fr["score"])))
    FRAMES[(tag, k)] = fr
    HACP[(tag, k)] = {
        "h_eff": h_eff,
        "hac_L": int(max(ac, h_eff - 1, 1)),
        "block": int(max(ac, h_eff, 1)),
    }
print(f"built {len(FRAMES)} eval frames")
if FRAMES:
    ex = next(iter(FRAMES))
    print(
        f"example {ex}: rows={len(FRAMES[ex])}  "
        f"usable r_fwd={int(FRAMES[ex]['r_fwd'].notna().sum())}  "
        f"HAC_L={HACP[ex]['hac_L']}  block={HACP[ex]['block']}"
    )
    display(FRAMES[ex].head())

"""### 9.2 Statistical skill

Directional and forecast-comparison tests. `hac_lrv` is the shared Newey–West
long-run variance used by DM and CW; the lag `HAC_L` is tied to the signal's
autocorrelation time so both dependence corrections are consistent.
"""


def hac_lrv(x, L):
    """Newey-West (Bartlett) long-run variance of one observation of x.

    gamma_0 + 2 * sum_{l=1..L} (1 - l/(L+1)) gamma_l. Shared by DM and CW so their
    SEs reflect the heavy serial correlation of tick-level loss differentials.
    """
    x = np.asarray(x, float)
    x = x[~np.isnan(x)]
    n = len(x)
    if n < 2:
        return np.nan
    x = x - x.mean()
    lrv = np.dot(x, x) / n
    for lag in range(1, min(L, n - 1) + 1):
        w = 1.0 - lag / (L + 1.0)
        lrv += 2.0 * w * np.dot(x[lag:], x[:-lag]) / n
    return max(lrv, 1e-24)


def hac_se_mean(x, L):
    """HAC standard error of the sample mean of x."""
    x = np.asarray(x, float)
    x = x[~np.isnan(x)]
    return np.sqrt(hac_lrv(x, L) / len(x))


def pesaran_timmermann(pred_sign, real_ret):
    """PT (1992) directional-accuracy test. pred_sign in {-1,0,+1}; flats dropped."""
    mask = ~np.isnan(real_ret) & (pred_sign != 0)
    x = (pred_sign[mask] > 0).astype(float)  # predicted up
    y = (real_ret[mask] > 0).astype(float)  # realized up
    n = len(y)
    if n < 10:
        return {"hit": np.nan, "benchmark": np.nan, "stat": np.nan, "p": np.nan, "n": n}
    P = float(np.mean(x == y))  # hit rate = sign agreement
    Py, Px = y.mean(), x.mean()
    Pstar = Py * Px + (1 - Py) * (1 - Px)  # independence benchmark
    var_P = Pstar * (1 - Pstar) / n
    var_Pstar = (
        ((2 * Py - 1) ** 2) * Px * (1 - Px) / n
        + ((2 * Px - 1) ** 2) * Py * (1 - Py) / n
        + 4 * Py * Px * (1 - Py) * (1 - Px) / n**2
    )
    denom = var_P - var_Pstar
    stat = (P - Pstar) / np.sqrt(denom) if denom > 0 else np.nan
    p = float(1 - stats.norm.cdf(stat)) if np.isfinite(stat) else np.nan
    return {"hit": P, "benchmark": Pstar, "stat": stat, "p": p, "n": n}


def henriksson_merton(pred_sign, real_ret):
    """HM market-timing skill: p_up + p_down - 1, hypergeometric significance."""
    mask = ~np.isnan(real_ret) & (pred_sign != 0)
    ps, rr = pred_sign[mask], real_ret[mask]
    up, dn = rr > 0, rr < 0
    n1, n2 = int(up.sum()), int(dn.sum())
    if n1 < 5 or n2 < 5:
        return {
            "skill": np.nan,
            "p_up": np.nan,
            "p_down": np.nan,
            "stat": np.nan,
            "p": np.nan,
        }
    p_up = float(np.mean(ps[up] > 0))  # correct given up
    p_dn = float(np.mean(ps[dn] < 0))  # correct given down
    n = n1 + n2
    N1 = int((ps > 0).sum())  # predicted up
    n11 = int(((ps > 0) & up).sum())  # correct up
    E = N1 * n1 / n
    V = N1 * n1 * (n - N1) * (n - n1) / (n**2 * (n - 1))
    stat = (n11 - E) / np.sqrt(V) if V > 0 else np.nan
    p = float(1 - stats.norm.cdf(stat)) if np.isfinite(stat) else np.nan
    return {
        "skill": p_up + p_dn - 1,
        "p_up": p_up,
        "p_down": p_dn,
        "stat": stat,
        "p": p,
    }


def diebold_mariano(r, f1, f2, L, h=1):
    """DM squared-error test, model f1 vs NON-NESTED baseline f2, HAC SE + HLN fix.

    d = e1^2 - e2^2; a significantly negative mean => model f1 has lower loss.
    """
    m = ~np.isnan(r) & ~np.isnan(f1) & ~np.isnan(f2)
    e1, e2 = r[m] - f1[m], r[m] - f2[m]
    d = e1**2 - e2**2
    n = len(d)
    if n < 10:
        return {"dbar": np.nan, "stat": np.nan, "p": np.nan, "n": n}
    se = hac_se_mean(d, L)
    stat = d.mean() / se if se > 0 else np.nan
    stat *= np.sqrt((n + 1 - 2 * h + h * (h - 1) / n) / n)  # Harvey-Leybourne-Newbold
    p = float(2 * (1 - stats.norm.cdf(abs(stat)))) if np.isfinite(stat) else np.nan
    return {"dbar": float(d.mean()), "stat": stat, "p": p, "n": n}


def clark_west(r, f_unrestr, f_restr, L):
    """CW test, model f_unrestr vs NESTED baseline f_restr (e.g. prevailing mean).

    f = (r - f_restr)^2 - [(r - f_unrestr)^2 - (f_restr - f_unrestr)^2]. The last
    term strips the estimation-noise penalty that biases plain DM against the
    larger model. One-sided: fbar>0 => the extra structure earns its keep OOS.
    """
    m = ~np.isnan(r) & ~np.isnan(f_unrestr) & ~np.isnan(f_restr)
    r_, fu, fr = r[m], f_unrestr[m], f_restr[m]
    f = (r_ - fr) ** 2 - ((r_ - fu) ** 2 - (fr - fu) ** 2)
    n = len(f)
    if n < 10:
        return {"fbar": np.nan, "stat": np.nan, "p": np.nan, "n": n}
    se = hac_se_mean(f, L)
    stat = f.mean() / se if se > 0 else np.nan
    p = float(1 - stats.norm.cdf(stat)) if np.isfinite(stat) else np.nan
    return {"fbar": float(f.mean()), "stat": stat, "p": p, "n": n}


def campbell_thompson_r2(r, f_model, f_mean):
    """OOS R^2 vs the prevailing mean; positive => model beats the running mean."""
    m = ~np.isnan(r) & ~np.isnan(f_model) & ~np.isnan(f_mean)
    num = np.sum((r[m] - f_model[m]) ** 2)
    den = np.sum((r[m] - f_mean[m]) ** 2)
    return float(1 - num / den) if den > 0 else np.nan


"""### 9.3 Economic value

Information coefficient, Fundamental Law with breadth deflation, conditional
separation, break-even cost, and calibration. Bootstrap CIs use circular blocks
of length `BLOCK_LEN` (the same autocorrelation time that set `HAC_L`).
"""


def block_bootstrap_ci(func, arrays, block, n_boot=None, ci=None, seed=0):
    """Circular-block-bootstrap CI for a statistic of one or more aligned arrays."""
    n_boot = N_BOOT if n_boot is None else n_boot
    ci = CI if ci is None else ci
    rng = np.random.default_rng(seed)
    arrays = [np.asarray(a, float) for a in arrays]
    n = len(arrays[0])
    nb = int(np.ceil(n / block))
    vals = []
    for _ in range(n_boot):
        starts = rng.integers(0, n, nb)
        idx = np.concatenate([(np.arange(s, s + block) % n) for s in starts])[:n]
        v = func(*[a[idx] for a in arrays])
        if np.isfinite(v):
            vals.append(v)
    vals = np.array(vals)
    lo, hi = np.percentile(vals, [100 * (1 - ci) / 2, 100 * (1 + ci) / 2])
    return float(np.mean(vals)), float(lo), float(hi)


def boot_group_diff(a, b, block, n_boot=None, ci=None, seed=3):
    """Block-bootstrap CI for mean(a) - mean(b) (each group resampled separately)."""
    n_boot = N_BOOT if n_boot is None else n_boot
    ci = CI if ci is None else ci
    rng = np.random.default_rng(seed)
    a, b = np.asarray(a, float), np.asarray(b, float)
    if len(a) < 2 or len(b) < 2:
        return np.nan, np.nan, np.nan

    def bmean(x):
        n = len(x)
        nb = int(np.ceil(n / block))
        s = rng.integers(0, n, nb)
        idx = np.concatenate([(np.arange(t, t + block) % n) for t in s])[:n]
        return x[idx].mean()

    d = np.array([bmean(a) - bmean(b) for _ in range(n_boot)])
    lo, hi = np.percentile(d, [100 * (1 - ci) / 2, 100 * (1 + ci) / 2])
    return float(d.mean()), float(lo), float(hi)


def _pearson(a, b):
    m = ~np.isnan(a) & ~np.isnan(b)
    return float(np.corrcoef(a[m], b[m])[0, 1]) if m.sum() > 2 else np.nan


def _spearman(a, b):
    m = ~np.isnan(a) & ~np.isnan(b)
    return float(stats.spearmanr(a[m], b[m]).correlation) if m.sum() > 2 else np.nan


def jonckheere_terpstra(groups):
    """JT trend test for monotone increase across ordered groups (normal approx)."""
    groups = [np.asarray(g, float) for g in groups]
    groups = [g[~np.isnan(g)] for g in groups]
    ns = np.array([len(g) for g in groups])
    N = ns.sum()
    JT = 0.0
    for i in range(len(groups)):
        for j in range(i + 1, len(groups)):
            diff = groups[j][:, None] - groups[i][None, :]  # Mann-Whitney count
            JT += np.sum(diff > 0) + 0.5 * np.sum(diff == 0)
    mu = (N**2 - np.sum(ns**2)) / 4.0
    var = (N**2 * (2 * N + 3) - np.sum(ns**2 * (2 * ns + 3))) / 72.0
    z = (JT - mu) / np.sqrt(var) if var > 0 else np.nan
    p = float(1 - stats.norm.cdf(z)) if np.isfinite(z) else np.nan  # one-sided (up)
    return {"JT": float(JT), "z": float(z) if np.isfinite(z) else np.nan, "p": p}


def brier_multiclass(probs, y):
    oh = np.eye(probs.shape[1])[y]
    return float(np.mean(np.sum((probs - oh) ** 2, axis=1)))


def murphy_decomposition(f, o, n_bins=None):
    """Binary Brier = Reliability - Resolution + Uncertainty (Murphy 1973).

    f = forecast prob, o in {0,1}. reliability lower is better; resolution higher.
    """
    n_bins = N_REL_BINS if n_bins is None else n_bins
    edges = np.linspace(0, 1, n_bins + 1)
    edges[-1] += 1e-9
    b = np.clip(np.digitize(f, edges) - 1, 0, n_bins - 1)
    obar = o.mean()
    rel = res = 0.0
    xs, ys, ns = [], [], []
    for k in range(n_bins):
        mask = b == k
        nk = int(mask.sum())
        if nk == 0:
            continue
        fk, ok = f[mask].mean(), o[mask].mean()
        rel += nk * (fk - ok) ** 2
        res += nk * (ok - obar) ** 2
        xs.append(fk)
        ys.append(ok)
        ns.append(nk)
    n = len(f)
    return {
        "reliability": rel / n,
        "resolution": res / n,
        "uncertainty": float(obar * (1 - obar)),
        "brier": float(np.mean((f - o) ** 2)),
        "bins": (np.array(xs), np.array(ys), np.array(ns)),
    }


# Run every statistical + economic metric on every (model, horizon). Results land
# in SIG[(tag, k)] (full dicts) and SIG_ROWS (one tidy record per pair).
def run_significance(tag, k):
    F = FRAMES[(tag, k)]
    hp = HACP[(tag, k)]
    L, block, h = hp["hac_L"], hp["block"], hp["h_eff"]
    ps, rf = F["dir_call"].to_numpy(), F["r_fwd"].to_numpy()
    rhat, rrw, rmean = (
        F["r_hat"].to_numpy(),
        F["r_rw"].to_numpy(),
        F["r_mean"].to_numpy(),
    )
    out = {}
    out["PT"] = pesaran_timmermann(ps, rf)
    out["HM"] = henriksson_merton(ps, rf)
    out["DM_rw"] = diebold_mariano(rf, rhat, rrw, L, h=h)
    out["CW"] = clark_west(rf, rhat, rmean, L)
    out["CT_R2"] = campbell_thompson_r2(rf, rhat, rmean)

    sc = F["score"].to_numpy()
    m = ~np.isnan(sc) & ~np.isnan(rf)
    sc_, rf_ = sc[m], rf[m]
    out["IC_pearson"] = (
        _pearson(sc_, rf_),
        *block_bootstrap_ci(_pearson, (sc_, rf_), block, seed=1)[1:],
    )
    out["IC_spearman"] = (
        _spearman(sc_, rf_),
        *block_bootstrap_ci(_spearman, (sc_, rf_), block, seed=2)[1:],
    )
    ic0 = _pearson(sc_, rf_)
    rho_hat = _pearson(sc_[1:], sc_[:-1])
    flam_rows = []
    for rho in sorted(set(RHO_GRID + [round(float(rho_hat), 3)])):
        defl = (1 - rho) / (1 + rho)
        br_eff = len(sc_) * defl
        flam_rows.append(
            {
                "rho": rho,
                "breadth_defl": defl,
                "BR_eff": br_eff,
                "IR": ic0 * np.sqrt(max(br_eff, 0.0)),
            }
        )
    out["FLAM"] = {
        "ic": ic0,
        "rho_hat": float(rho_hat),
        "table": pd.DataFrame(flam_rows),
    }

    pc = F["pred_class"].to_numpy()
    grp = {c: rf[(pc == c) & ~np.isnan(rf)] for c in (0, 1, 2)}
    edge = boot_group_diff(grp[2], grp[0], block)
    out["SEP"] = {
        "means_bp": {
            c: float(np.nanmean(grp[c]) * 1e4) if len(grp[c]) else np.nan for c in grp
        },
        "edge_bp": (edge[0] * 1e4, edge[1] * 1e4, edge[2] * 1e4),
        "JT": jonckheere_terpstra([grp[0], grp[1], grp[2]]),
    }

    c = float(F["cost"].iloc[0])
    dcall = F["dir_call"].to_numpy()
    dmask = (dcall != 0) & ~np.isnan(rf)
    pnl = dcall[dmask] * rf[dmask]
    up_mask = (pc == 2) & ~np.isnan(rf)
    up_move = float(np.nanmean(rf[up_mask])) if up_mask.any() else np.nan
    rhat_mag = np.abs(rhat[dmask])
    clears = float(np.mean(rhat_mag > c)) if len(rhat_mag) else np.nan
    wins, losses = pnl[pnl > 0], -pnl[pnl < 0]
    W = wins.mean() if len(wins) else np.nan
    Lm = losses.mean() if len(losses) else np.nan
    p_star = (Lm + c) / (W + Lm) if np.isfinite(W + Lm) and (W + Lm) > 0 else np.nan
    out["BE"] = {
        "up_move_bp": up_move * 1e4,
        "cost_bp": c * 1e4,
        "frac_clears": clears,
        "W_bp": W * 1e4,
        "L_bp": Lm * 1e4,
        "p_star": float(p_star) if np.isfinite(p_star) else np.nan,
        "hit": float(np.mean(pnl > 0)) if len(pnl) else np.nan,
    }

    probs = RESULTS[(tag, k)]["probs"]
    yv = RESULTS[(tag, k)]["y_true"]
    out["BRIER_MC"] = brier_multiclass(probs, yv)
    out["MURPHY"] = murphy_decomposition(probs[:, 2], (yv == 2).astype(float))
    return out


SIG, SIG_ROWS = {}, []
for tag, k in sorted(RESULTS, key=lambda tk: (tk[1], tk[0])):
    if (tag, k) not in FRAMES:
        continue
    r = run_significance(tag, k)
    SIG[(tag, k)] = r
    SIG_ROWS.append(
        {
            "model": DISPLAY[tag],
            "k": k,
            "pt_hit": r["PT"]["hit"],
            "pt_p": r["PT"]["p"],
            "hm_skill": r["HM"]["skill"],
            "hm_p": r["HM"]["p"],
            "dm_dbar": r["DM_rw"]["dbar"],
            "dm_p": r["DM_rw"]["p"],
            "cw_fbar": r["CW"]["fbar"],
            "cw_p": r["CW"]["p"],
            "ct_r2_pct": r["CT_R2"] * 100,
            "ic_pearson": r["IC_pearson"][0],
            "ic_spearman": r["IC_spearman"][0],
            "ir_rho_hat": float(
                r["FLAM"]["table"].iloc[
                    (r["FLAM"]["table"]["rho"] - r["FLAM"]["rho_hat"]).abs().idxmin()
                ]["IR"]
            ),
            "rho_hat": r["FLAM"]["rho_hat"],
            "edge_bp": r["SEP"]["edge_bp"][0],
            "jt_p": r["SEP"]["JT"]["p"],
            "be_pstar": r["BE"]["p_star"],
            "be_hit": r["BE"]["hit"],
            "frac_clears": r["BE"]["frac_clears"],
            "brier_mc": r["BRIER_MC"],
            "reliability": r["MURPHY"]["reliability"],
            "resolution": r["MURPHY"]["resolution"],
        }
    )
sig_df = pd.DataFrame(SIG_ROWS)
print(f"scored {len(SIG)} (model, horizon) pairs")
sig_df

"""> **On the tiny $R^2_{\text{OOS}}$.** At LOB frequency a Campbell–Thompson
> $R^2$ below ~1% is *expected*, not a failure: forward mid returns are almost
> pure noise, so even a real edge explains little variance. What matters is
> whether that sliver is (a) statistically robust (DM/CW above) and (b)
> economically large after the trade multiplier — quantified in the economic
> layer next.

> **Calibration is only load-bearing if you size on probabilities.** If the
> strategy just acts on the argmax class, skip the Brier / Murphy block; it
> matters when `p_up` drives position size, where a well-resolved, low-reliability
> forecast can be scaled and a miscalibrated one cannot.
"""

# Reliability diagrams (up-vs-rest) — one panel per model at a focus horizon.
# Only meaningful for probability-sized strategies.
if SIG:
    ks = sorted({k for _, k in SIG})
    focus_k = REL_FOCUS_K if REL_FOCUS_K in ks else ks[0]
    tags = [t for t in MODELS if (t, focus_k) in SIG]
    if tags:
        ncol = min(4, len(tags))
        nrow = int(np.ceil(len(tags) / ncol))
        fig, axes = plt.subplots(
            nrow, ncol, figsize=(3.4 * ncol, 3.4 * nrow), squeeze=False
        )
        for ax in axes.flat:
            ax.axis("off")
        for ax, tag in zip(axes.flat, tags):
            ax.axis("on")
            mp = SIG[(tag, focus_k)]["MURPHY"]
            xs, ys, ns = mp["bins"]
            ax.plot([0, 1], [0, 1], "k--", lw=1)
            if len(ns):
                ax.scatter(
                    xs, ys, s=15 + 200 * (ns / ns.max()), color="#1f77b4", zorder=3
                )
            ax.set_title(
                f"{DISPLAY[tag]}\nrel={mp['reliability']:.4f} "
                f"res={mp['resolution']:.4f}",
                fontsize=8,
            )
            ax.set_xlim(0, 1)
            ax.set_ylim(0, 1)
            ax.set_xlabel("forecast P(up)", fontsize=8)
            ax.set_ylabel("emp. freq(up)", fontsize=8)
        fig.suptitle(f"Reliability (up-vs-rest) — horizon k={focus_k}", y=1.02)
        plt.tight_layout()
        save_fig(fig)
        plt.show()

"""### 9.4 Summary tables (all models × horizons)

One pivot per headline metric (rows = model, cols = horizon). Statistical tests
also print a companion p-value pivot so significance is read alongside the point
estimate.
"""

if not sig_df.empty:
    order = [DISPLAY[m] for m in MODELS if DISPLAY[m] in set(sig_df["model"])]

    def pivot(col, fmt="{:.4f}", cmap="YlGn"):
        piv = sig_df.pivot(index="model", columns="k", values=col).reindex(order)
        return piv.style.background_gradient(cmap=cmap, axis=None).format(fmt)

    # value + p-value pairs for the statistical tests
    stat_specs = [
        ("Pesaran-Timmermann hit rate", "pt_hit", "pt_p"),
        ("Henriksson-Merton skill", "hm_skill", "hm_p"),
        ("Diebold-Mariano dbar (vs persistence)", "dm_dbar", "dm_p"),
        ("Clark-West fbar (vs prev-mean)", "cw_fbar", "cw_p"),
    ]
    for title, vcol, pcol in stat_specs:
        print(f"\n=== {title} — value (rows=model, cols=k) ===")
        display(pivot(vcol))
        print("    p-value")
        display(
            sig_df.pivot(index="model", columns="k", values=pcol)
            .reindex(order)
            .style.background_gradient(cmap="Reds_r", axis=None, vmin=0, vmax=0.1)
            .format("{:.4g}")
        )

    # single-table economic / directional metrics
    econ_specs = [
        ("Campbell-Thompson OOS R^2 (%)", "ct_r2_pct"),
        ("IC Pearson", "ic_pearson"),
        ("IC Spearman", "ic_spearman"),
        ("Implied IR @ rho_hat (breadth-deflated)", "ir_rho_hat"),
        ("Edge E[r|up]-E[r|down] (bp)", "edge_bp"),
        ("Jonckheere-Terpstra p (monotone)", "jt_p"),
        ("Break-even hit p*", "be_pstar"),
        ("Realized directional hit rate", "be_hit"),
        ("Frac predictions clearing cost", "frac_clears"),
        ("Brier reliability (lower better)", "reliability"),
        ("Brier resolution (higher better)", "resolution"),
    ]
    for title, col in econ_specs:
        print(f"\n=== {title} (rows=model, cols=k) ===")
        cmap = "Reds_r" if col == "jt_p" else "YlGn"
        fmt = "{:.4g}" if col in ("jt_p",) else "{:.4f}"
        display(pivot(col, fmt=fmt, cmap=cmap))
else:
    print("No results — run the sections above first.")

"""### 9.5 What a pass looks like — per metric

Each line states the pass condition and the claim it licenses.

- **Pesaran–Timmermann** — *pass:* `p < 0.05` and hit > benchmark. *Claim:* the
  predicted direction and the realized sign are dependent — genuine directional
  information, not the marginal class mix.
- **Henriksson–Merton** — *pass:* skill `> 0` with `p < 0.05`. *Claim:* the model
  times **both** sides (its up-hit and down-hit rates jointly beat coin-flipping),
  not just one lucky regime.
- **Diebold–Mariano** — *pass:* `dbar < 0` with `p < 0.05`. *Claim:* the model's
  squared forecast error is reliably below the persistence baseline's — lower loss
  than a non-nested competitor, beyond sampling noise.
- **Clark–West** — *pass:* `fbar > 0` with one-sided `p < 0.05`. *Claim:* the
  model beats the nested prevailing-mean forecast out-of-sample *after* removing
  the estimation-noise advantage — the extra structure earns its keep, not
  overfitting.
- **Campbell–Thompson OOS $R^2$** — *pass:* `> 0` (even ~0.1–1%). *Claim:* the
  model adds predictive information over the running mean; magnitude is expected
  to be tiny at LOB frequency — economic size is judged below, not here.
- **Information coefficient** — *pass:* CI excludes 0. *Claim:* score and forward
  return are monotonically related (Spearman) / linearly related (Pearson) beyond
  autocorrelation-inflated noise.
- **Fundamental Law (IR)** — *pass:* deflated IR stays economically meaningful
  (rule-of-thumb `> 0.5`) at the *estimated* `rho_hat`, not just at `rho=0`.
  *Claim:* after honestly discounting breadth for signal persistence, the implied
  information ratio is still worth harvesting.
- **Conditional separation / Jonckheere–Terpstra** — *pass:* edge CI excludes 0
  **and** JT `p < 0.05`. *Claim:* mean forward return increases monotonically
  down→flat→up — the classes sort future returns in the right order.
- **Break-even cost** — *pass:* realized hit `> p*` and a non-trivial fraction of
  calls clear the cost hurdle. *Claim:* the edge survives the round-trip cost —
  the signal is tradeable, not just correlated.
- **Calibration (Brier / Murphy)** — *pass:* low reliability, positive resolution,
  reliability curve near the diagonal. *Claim:* `p_up` can be trusted for position
  **sizing**, not only for its argmax label.
"""
